### PR TITLE
OIDC Configuration Error

### LINKED ISSUE #2603: OIDC Config has wrong QName for OAuthSelectionStrategy
Working with latest 5.1.0-SNAPSHOT in master.

OidcConfiguration.java has the wrong Qualifier name for the OAuth Selection Strategy bean.  Causes a dependency error when deploying.

Submitting Pull Request with fix.

### PR DESCRIPTION
**Pull request by tsschmidt**
Closes #2603

### CODE REVIEW

**Comment by mmoayyed** [comment]
This patch breaks the CAS configuration, as the correct bean id is in fact `oauth20AuthenticationRequestServiceSelectionStrategy`. With the new change, CAS starts to complain about the missing bean id.

**Comment by tsschmi** [comment]
Sorry about that.  Looks like I messed up a  merge on my end or something
and changed that id for some reason.

My apologies.
Travis

**Comment by tsschmi** [comment]
So is it OidcConfiguration need to change then?


@Autowired
@Qualifier("oauth20AuthenticationServiceSelectionStrategy")
private AuthenticationServiceSelectionStrategy
oauth20AuthenticationServiceSelectionStrategy;

**Comment by tsschmi** [comment]
Never mind that was the error I introduced.  Now I have it straight

**Comment by mmoayyed** [comment]
All good. No worries. I am going to correct this shortly, plus a few other minor UI tweaks to OIDC consent.

**Pull request merged**
