### PR TITLE
AUP: Do not require TGT before AUP execution

### PR DESCRIPTION
**Pull request by MartinBoehmer**
Bugfix: AbstractPrincipalAttributeAcceptableUsagePolicyRepository is using a [method that requires a TGT to be present](https://github.com/apereo/cas/blob/d7625070c99e10afb53e26feee6df79a706b9de5/support/cas-server-support-aup-core/src/main/java/org/apereo/cas/aup/AbstractPrincipalAttributeAcceptableUsagePolicyRepository.java#L41). However, AUP is executed BEFORE TGTs are created, so use other method to get principal. This bug caused an [IllegalArgumentException](https://github.com/apereo/cas/blob/3c47d350f6643283196c146865e0613e7342e342/core/cas-server-core-web-api/src/main/java/org/apereo/cas/web/support/WebUtils.java#L501) corrupting the entire login flow.

JDBC improvements: The database update of the AUP acceptance can now be configured in a very flexible way, if necessary. The defaults ensure backward compatibility of older production configurations.

Documentation updates still pending, will be provided soon.

### CODE REVIEW

**Comment by MartinBoehmer** [comment]
I would like to see the non-bugfix changes in a future 5.3 release as this is our production environment. Would that be possible?

**Comment by mmoayyed** [comment]
Generally, no though that depends on your patch and what it wants to do (and the policy is pretty forgiving in that regard). If you break this pull request apart, it'd be easier to decipher the extent of the change and whether it'd be applicable to accept here.

**Comment by MartinBoehmer** [comment]
Okay. I'll split this into separate PRs. However, I would like to see the non-bugfix changes in a future 5.3 release as this is our production environment. Would that be possible?

**Comment by MartinBoehmer** [comment]
Sorry, last post was an unintended duplicate. I reverted all non-bugfix changes from this PR and created a new PR for them: #3733

**Comment by mmoayyed** [comment]
Thank you very much. I think this looks fine, and I have asked Hal to also review. We should be able to merge in no time. You should start prepping for the branches and porting the change to those, unless you rather we handle that for you. 

Thanks again! excellent work.

**Comment by MartinBoehmer** [comment]
Thanks, I already created branches for ports to 6.0 and master.

**Comment by MartinBoehmer** [comment]
Is there anything left to do here?
The current CI build fail has reasons beyond this PR:

> Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'https://jcenter.bintray.com/com/jcraft/jsch.agentproxy.jsch/0.0.9/jsch.agentproxy.jsch-0.0.9.pom'

**Pull request merged**
