### PR TITLE
Mark beans conditional to allow redefinition by implementors (master)

### PR DESCRIPTION
**Pull request by robertoschwald**
same as #2601 but for master.

see #2600

### CODE REVIEW

**Comment by mmoayyed** [comment]
Thank you!

**Comment by robertoschwald** [comment]
NP. Whats this codacy bug? False positive?

**Comment by mmoayyed** [comment]
Yes, likely. It probably does not like the fact that we have "duplicate" annotations. This thing is hit and miss mostly.

**Comment by mmoayyed** [comment]
This change break the CAS validation endpoints by default due to the @Controller annotation pre-scanning the content. The bean definitions, now marked as conditional, are never injected into the context due to that pre-scan.

**Comment by robertoschwald** [comment]
I'll check now

**Comment by mmoayyed** [comment]
I am working on a solution that shows some promise; the trick is to move the annotation for @Controller to the parent classes so Boot does not create a bean apriori. You may want to check this for 5.0.x.

**Comment by robertoschwald** [comment]
ok, I'll wait and check on 5.0.x

**Comment by mmoayyed** [comment]
I can confirm that marking controllers as Conditional breaks CAS in 5.0.x. This is fixed in master, and the issue has to do with the following sequence:

- Boot scans the context and creates beans that are annotated with @Controller, specially the validation controllers.
- Because the explicit Bean definitions are now marked as conditional, Boot never creates the proper instance with all of its injections
- Controls result in NPEs due to missing injections.

The trick is to remove the Controller annotation from the individual validation controllers and move them to the parent abstract class, so Boot can still recognize and register them in the servlet chain, but not create an instance of them beforehand.

Please let me know if you have time time to review this, or if you'd rather I apply the same change to 5.0.x to make this work.

**Comment by robertoschwald** [comment]
I'll review now

**Comment by robertoschwald** [comment]
Will implement fix tomorrow, as I had to interrupt.

**Comment by robertoschwald** [comment]
@mmoayyed Cannot reproduce the problem here. Sent you a PM on Gitter.

**Comment by mmoayyed** [comment]
Thanks for checking. Let me run through this once more.

**Pull request merged**
