### PR TITLE
Fix conflicting SessionStore bean declarations

### PR DESCRIPTION
**Pull request by mtritschler**
When using OIDC alongside Delegated Authentication (i.e. where CAS acts as OIDC provider but also optionally offers Social Login) CAS wouldn't start because the application context contained two instances of SessionStore beans and Spring couldn't decide which bean should be injected into `DelegatedClientNavigationController`.

```
2019-07-25 07:58:20,748 WARN [org.apereo.cas.web.CasWebApplicationContext] - <Exception encountered during context initialization - cancelling refresh attempt:
 org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'delegatedClientNavigationController' defined in URL [jar:file:/path/to/app.jar!/WEB-
INF/lib/cas-server-support-pac4j-webflow-6.1.0-RC5-SNAPSHOT.jar!/org/apereo/cas/web/DelegatedClientNavigationController.class]: Unsatisfied dependency expressed through constructor
 parameter 2; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.pac4j.core.context.session.SessionStore<?>' 
available: expected single matching bean but found 2: oauthDistributedSessionStore,delegatedClientDistributedSessionStore>
```

There are two ways to go about this.

1. Ensure that there's only a single instance of a SessionStore in the application context - could just remove the `name`-parameter from the `@ConditionalOnMissingBean` to have it check for existence of a bean with the same type instead of by name.
2. Qualify the name of the bean Spring should inject into the Controller

The first commit in this PR shows what Option 1 would look like, but in the end I decided to go with Option 2, since a) the SessionStore bean is stateless and it will hit the same underlying TicketRegistry from both instances anyway and b) there are a couple of places where the bean is qualified by name, which would all have to be changed.

- [x] Brief description of changes applied
- [x] Test cases for all modified changes, where applicable: Should be covered by existing tests
- [x] The same pull request targetted at the master branch, if applicable
- [x] Any documentation on how to configure, test: Doesn't apply, I suppose
- [x] Any possible limitations, side effects, etc
- [x] Reference any other pull requests that might be related: None

### CODE REVIEW

**Comment by mmoayyed** [comment]
Can you provide a sample project that duplicates this please?

**Comment by mtritschler** [comment]
@mmoayyed please take a look at https://github.com/mtritschler/cas-demo

**Comment by hdeadman** [comment]
@mtritschler, Are you tracking the checkstyle issues?
```
[ant:checkstyle] [ERROR] /home/travis/build/apereo/cas/webapp/cas-server-webapp-init-config-server/src/main/java/org/apereo/cas/CasConfigurationServerWebApplication.java:27:8: Unused import - org.springframework.boot.autoconfigure.security.servlet.PathRequest. [UnusedImports]
2052
[ant:checkstyle] [ERROR] /home/travis/build/apereo/cas/webapp/cas-server-webapp-init-config-server/src/main/java/org/apereo/cas/CasConfigurationServerWebApplication.java:35:8: Unused import - org.springframework.security.config.annotation.web.builders.WebSecurity. [UnusedImports]
```

**Comment by mmoayyed** [comment]
Have you tried running your sample project with the latest RC5 snapshots?

**Comment by mtritschler** [comment]
@mmoayyed, I can't reproduce the issue anymore with the latest RC5 snapshot, thanks. What was the change that fixed it?

**Comment by mmoayyed** [comment]
Quite likely, the pac4j upgrade.

**Pull request closed without merging**
