### PR TITLE
Port MDUI bean def fixes to 5.3 branch

### PR DESCRIPTION
**Pull request by rrenomeron**
Porting commit 6d4b11ff615e20e2661a7dfd374433520956651a to 5.3.x branch, so I can use the saml mdui.

### CODE REVIEW

**Comment by mmoayyed** [comment]
@rrenomeron thank you! I'd like for this to be included in the coming 5.3.x patch release. Do you think you could fix the build here before Monday?

**Comment by auxepaul** [comment]
Same fix required in 6.0.x : https://github.com/apereo/cas/blob/6.0.x/support/cas-server-support-saml-mdui/src/main/java/org/apereo/cas/support/saml/mdui/config/SamlMetadataUIWebflowConfiguration.java#L67?

**Comment by mmoayyed** [comment]
Yes. Quite likely, this can also be ported forward with another pull request.

**Comment by rrenomeron** [comment]
Will submit PR for the 6.0 branch shortly, certainly by Monday.

**Comment by mmoayyed** [comment]
Thank you; no rush there. We have a couple of weeks before the set release date...and thanks again for taking care of this.

**Pull request merged**
