### PR TITLE
fix wss4jVersion

### PR DESCRIPTION
**Pull request by jiangying000**
seems wss4j has highest version of 3.0.0, https://search.maven.org/artifact/org.apache.wss4j/wss4j-ws-security-common
wss4jVersion=4.0.0 does not exists in maven repo, so I try to change that to 3.0.0

### CODE REVIEW

**Comment by jiangying000** [comment]
> It appears that this pull request attempts to upgrade one or more CAS dependencies to a newer version, and this patch is likely targeted at a CAS branch that is no longer maintained and has reached end of life, or, the targeted CAS version has gone into maintenance mode.

i think it's not true

**Comment by leleuj** [comment]
Indeed, this is an inappropriate message and I also think we have an issue with this dependency.

**Comment by leleuj** [comment]
Some update here: we need a new release of wss4j (v4.0.0) based on OpenSAML v5. Until then, the build uses a custom Maven repo. This will be fixed ASAP.
For now, you can locally use the version 3.0.0.

**Comment by jiangying000** [comment]
> Some update here: we need a new release of wss4j (v4.0.0) based on OpenSAML v5. Until then, the build uses a custom Maven repo. This will be fixed ASAP. For now, you can locally use the version 3.0.0.

Got, thanks for the info

**Comment by hdeadman** [comment]
I fixed this locally (for myself) by cloning: https://github.com/mmoayyed/ws-wss4j/tree/opensamlv5 (opensamlv5 branch or that repo) and running `mvn install`.

**Comment by leleuj** [comment]
Thanks for sharing. This is indeed the best solution.

**Pull request closed without merging**
