### PR TITLE
Add LinkedIn delegated authN support for CAS 5.0.x

### LINKED ISSUE #2101: Delegated Authentication for LinkedIn using Pac4j
Would like to request CAS5(for 5.0.0.RC4-SNAPSHOT) Delegated Authentication for linkedin . 
Please see below 
https://groups.google.com/a/apereo.org/forum/#!searchin/cas-user/linkedin/cas-user/tNRb1fkOUVY/Wz5JEoVGAgAJ

### PR DESCRIPTION
**Pull request by yellowcola**
Closes #2101 

Ensure that you include the following:

**Description**
add LinkedIn support for CAS 5.0.x.

**Configuration**
To enable, add following config to application.properites
`cas.authn.pac4j.linkedIn.id=`
`cas.authn.pac4j.linkedIn.secret=`
`cas.authn.pac4j.linkedIn.fields=`
`cas.authn.pac4j.linkedIn.scope=`

### CODE REVIEW

**Comment by mmoayyed** [comment]
Thanks. Does pac4j plan on releasing a 1.9.6?

**Comment by yellowcola** [comment]
Yes, based on PR I submitted last night.
https://github.com/pac4j/pac4j/pull/819

**Comment by mmoayyed** [comment]
Great. Excellent work. When 1.9.6 is released, please update the PR and we can perfectly merge :)

**Comment by yellowcola** [comment]
Got it. Thanks!

**Comment by mmoayyed** [comment]
One last thing: please also update the docs to note the new settings. Follow the same format as other providers

**Comment by leleuj** [comment]
We can plan the 1.9.6 release for the end of February if it's not too late for CAS 5.0.x.

**Comment by mmoayyed** [comment]
The current schedule is Feb 17th. We can probably postpone for a few days until 1.9.6 is released, or push this PR into 5.0.4

**Comment by leleuj** [comment]
No problem, I'll cut the 1.9.6 release sooner. Ping me if I forget.

**Comment by mmoayyed** [comment]
Excellent. Thanks Jérôme

**Comment by yellowcola** [comment]
Thanks, @leleuj

**Comment by mmoayyed** [comment]
hey @yellowcola not a requirement at all, but would you want to sign the CLA here? Makes things easier going fwd but as I said, not a requirement at all for contributors.

**Comment by leleuj** [comment]
I just released pac4j v1.9.6. It should be available in the Maven Central repository within a few hours.

**Comment by mmoayyed** [comment]
Thanks @leleuj

**Pull request merged**
