### PR TITLE
WIP: remove Spring modules

### PR DESCRIPTION
**Pull request by leleuj**
The `springmodules` project has been abandoned a long time ago.

### CODE REVIEW

**Comment by leleuj** [comment]
@mmoayyed Thanks for merging.

In fact, the unit and Puppeteer tests related to the JSON services registry were OK (locally because of wss4j v4), but I was still doing manual tests (hence the "WIP").

And I faced an issue. Though, this is not related to this change. Since that commit: https://github.com/apereo/cas/commit/099cdacafe3ef9430f0639b90783d61c8beaeeea, it seems that lazy initialization has side effects: I don't see the reloading of the services anymore, the `CasCoreServicesSchedulingConfiguration` bean is not called at startup anymore.

I think there is something broken now.

**Comment by mmoayyed** [comment]
Yes that is true. This is a work in progress; should be fixed shortly. (Listeners should generally be marked as non-lazy) Running tests...

**Comment by leleuj** [comment]
OK. No problem if you already have that in your sights.

**Comment by leleuj** [comment]
The services reloading is still broken, but hopefully the fix is easy: https://github.com/apereo/cas/pull/5586

**Pull request merged**
