### PR TITLE
unified oauth token expiration policy attribute name

### PR DESCRIPTION
**Pull request by zawn**
Unified token expiration policy。
Before timeToKillInSeconds, maxTimeToLiveInSeconds different meanings in different tokens, misleading。
Refresh token should have number of uses limitations，
Change will allow administrators to use a more appropriate strategy：
For example, long-term effective refresh token, failure only after a defined number of times

### CODE REVIEW

**Comment by mmoayyed** [comment]
Fix the formatting issues first so we can review. Thanks.

**Comment by mmoayyed** [comment]
This will not make the cut for 5. I assigned this to @leleuj who's more familiar with this area to review.

**Comment by mmoayyed** [comment]
Also I am not sure it makes sense for a refreshToken to ever expire after # number of attempts. I get that you are trying to make the organization of settings more consistent, but that change would not make sense to me.

**Comment by zawn** [comment]
Thanks

**Comment by mmoayyed** [comment]
This will need to be rebased

**Pull request closed without merging**
