### PR TITLE
Use authn attribute release policy for resource password grant type

### PR DESCRIPTION
**Pull request by leleuj**
To follow our Slack discussion and the previous PR: https://github.com/apereo/cas/pull/5524

### CODE REVIEW

**Comment by mmoayyed** [comment]
Thank you. 

I think I have also found a somewhat elegant solution for the 2nd problem we discussed, which I am going to test on top of your changes and see how it would work. If so, then most likely we'll merge this out of band. More next week.

**Comment by leleuj** [comment]
Backported to 6.6.x: https://github.com/apereo/cas/pull/5529

**Comment by leleuj** [comment]
@apereocas-bot run

**Comment by leleuj** [comment]
Thanks for your help

**Comment by mmoayyed** [comment]
Yes I think this should be somewhat handled in master. You should be able to review the following puppeteer tests to see how this would work:

1. oidc-authn-claims-freeform
2. oidc-authn-claims-scoped

The first once releases and polishes authn attributes without a defined scope in a free-form way, and the second one bundles those into a scope that could be requested by the client.

Services in general could also use flag `authorizedToReleaseAuthenticationAttributes` attribute to indicate the release of authn attributes, and this also passes through the same authn attribute release policy that you are using.

**Comment by leleuj** [comment]
Great! I will check that today.

**Comment by leleuj** [comment]
This works perfectly! In OAuth v2 also. Thanks.

**Comment by misaghmo** [comment]
Hurray!

**Comment by mmoayyed** [comment]
Hurray!

**Pull request merged**
