### PR TITLE
Revert back to compatible MFA Failure Mode option

### PR DESCRIPTION
**Pull request by tsschmidt**
Changes the "UNDEFINED" from Failure mode enum option back to "NOT_SET".  Removing NOT_SET will cause existing services in registries to error.  

We can either add NOT_SET and keep both or write a mapper to set NOT_SET to UNDEFINED.

### CODE REVIEW

**Comment by mmoayyed** [comment]
>... or write a mapper to set NOT_SET to UNDEFINED.

This is not necessary because the very same `RegisteredServiceMultifactorPolicyDeserializationProblemHandler.java` you modified here should handle scenarios where NOT_SET can be translated to UNDEFINED. Everything that passes through that handler should be caught, and there is a test case that demonstrates this. If you find other registries that don't pass through the Jackson library, those are the ones you should review and fix.

**Comment by tsschmidt** [comment]
Ok, yeah, I didn't really look close enough to what I was modifying.  I
think where I am seeing the issue is only when using default jackson mapper
with  Spring when sending the service over the wire between the client and
the server.  Looks like I need to find a way to configure Spring to use the
problem handler when serializing/de-serializing services for REST endpoints?

**Comment by mmoayyed** [comment]
Yes. If you use `DefaultRegisteredServiceJsonSerializer` as the thing that handles the serialization, then it would automatically do that for you...or at least, it should.

**Comment by tsschmidt** [comment]
Closing, wrong approach.  Will fix by customizing Jackson mapper in CAS Management to use the problem handler

**Pull request closed without merging**
