### PR TITLE
This patch allows to load SAML metadata according to the browser language

### PR DESCRIPTION
**Pull request by lsenecaux**
Not being a JAVA developer, I do not know if this patch conforms to your development rules.

See #2735

### CODE REVIEW

**Comment by mmoayyed** [comment]
This is perfect. Thank you. 

- Do not worry about "making mistakes": https://apereo.github.io/cas/developer/Contributor-Guidelines.html#be-not-afraid
- Would you be interested in issuing the same changeset to the master branch?

**Comment by lsenecaux** [comment]
Yes, I'll try to submit this to the master branch in few days.
Can I include  your changes (issues #2735, #2740) in branch 5.1.x too ?

**Comment by mmoayyed** [comment]
Sure. You're welcome to backport any and all changes you deem appropriate that remove pain :)

**Comment by lsenecaux** [comment]
Great !

**Comment by mmoayyed** [comment]
Also, if it helps there is this guide: https://apereo.github.io/2017/07/05/cas-contribution-guide/

**Pull request merged**
