### PR TITLE
Fix polish translations

### PR DESCRIPTION
**Pull request by marcinroman**
Corrected some translations and reformatted file.

### CODE REVIEW

**Comment by mmoayyed** [comment]
Thanks much. Please make sure you have the same PR for the main master branch as well.

**Review by mmoayyed — CHANGES_REQUESTED** [review]
Thanks much. Please make sure you have the same PR for the main master branch as well.

**Comment by marcinroman** [comment]
Hi, currently this file is identical in master and 6.3.x branch. Do I have to create the same PR to master branch?

**Comment by mmoayyed** [comment]
If the changes you have here already exist in master, then no you can skip that.

Generally, yes, you should always have two PRs when you are targeting
maintenance branches unless you want us to cherry pick the change for
you, which in this case might be possible since changes are trivial.

**Comment by mmoayyed** [comment]
So to clarify: your changes here already do exist in the master branch, right?

**Comment by marcinroman** [comment]
I have just created similar PR for master branch: #5040

**Comment by mmoayyed** [comment]
Thank you very much for the contribution. Keep 'em coming!

**Pull request merged**
