### PR TITLE
Fix issue that JpaTicketRegist can not  presist OAuth Tickets

### PR DESCRIPTION
**Pull request by yisiqi**
Fix issue that JpaTicketRegist can not  presist OAuth Tickets

### CODE REVIEW

**Comment by mmoayyed** [comment]
Thanks very much for the patch. Before we proceed, could I ask you to provide the following?

- a clear explanation of the problem and when it manifests, how.
- a clear explanation of why said problem is solved by your patch.

**Comment by yisiqi** [comment]
The JpaTicketRegistry always throw this:
```
java.lang.IllegalArgumentException: Unknown entity: org.apereo.cas.support.oauth.ticket.code.OAuthCodeImpl
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1149) ~[hibernate-entitymanager-5.1.0.Final.jar:5.1.0.Final]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:298) ~[spring-orm-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at com.sun.proxy.$Proxy171.persist(Unknown Source) ~[?:?]
	at org.apereo.cas.ticket.registry.JpaTicketRegistry.addTicket(JpaTicketRegistry.java:58) ~[cas-server-support-jpa-ticket-registry-5.0.0.RC1-SNAPSHOT.jar:5.0.0.RC1-SNAPSHOT]
	at org.apereo.cas.ticket.registry.JpaTicketRegistry$$FastClassBySpringCGLIB$$84ce3a7e.invoke(<generated>) ~[cas-server-support-jpa-ticket-registry-5.0.0.RC1-SNAPSHOT.jar:5.0.0.RC1-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
...
```

I checked the `JpaTicketRegistryConfiguration`. The `EntityManagerFactory` will only scan entities under `org.apereo.cas.ticket` and `org.apereo.cas.adaptors.jdbc`.

I think move `org.apereo.cas.support.oauth.ticket` to `org.apereo.cas.ticket` will resolve this.

**Comment by mmoayyed** [comment]
Great. Fix the build failures please.

**Comment by yisiqi** [comment]
Ok, the build failures fixed.

**Pull request merged**
