### PR TITLE
@UtilityClass already transforms all methods to `static`

### PR DESCRIPTION
**Pull request by dima767**
Minor polishing for code consistency

### CODE REVIEW

**Comment by mmoayyed** [comment]
Thanks for the patch!

This looks good in theory on the surface. However,

- Often most IDEs have trouble understanding constructs generated by lombok, which makes it difficult for native-IDE inspections to differentiate between methods that are marked as static vs those that should but are not. This means that removing the keyword static (even though it's there) creates unnecessary warnings during development.

- The same principal holds true for most other static analysis tools.

- If the above two issues were m00t, making this sort of change cannot be an isolated incident as for consistency sake, the same sort of practice must be done sweepingly in all places that use this annotation; something I suspect you might be prepared to do(?)

Given above, I don't think the patch can be accepted.

**Comment by dima767** [comment]
I could live with either:-) 

It's just on the personal preference level then - why bother with `@UtilityClass` for example. Just use language constructs explicitly :-) (this could be open for endless debates) :-) 

What caught my attention wrt "consistency" is that all other methods in `LoggingUtils` class are already non-static at the source level and taking lombok's transformation into consideration.

In any case, not a big deal to me, and could be closed.

**Comment by mmoayyed** [comment]
Thanks for the notes. They all should be marked as static, and I see a few missing per your notes. You could make that change, of it's easier, I can do it on your behalf.

**Comment by dima767** [comment]
OK, I'll re-open and make them static (just in that class), unless you'd want me to check all `@UtilityClass`troughout the code base

**Comment by mmoayyed** [comment]
Thanks. We can just scope it to the components you have here.

**Comment by dima767** [comment]
👍

**Pull request merged**
