### PR TITLE
Removal of Cascading tickets does not honor cas.properties in JpaTicketRegistry

### PR DESCRIPTION
**Pull request by ThomasSeliger**
I tryed to put together a testcases to Illustrate the failing cascade removals of oauth tokens in case the property "cas.logout.remove-descendant-tickets" is set to false.
Also this PR does change the setting of setExcludeFromCascade inside CasOAuth20ProtocolTicketCatalogConfiguration, so it does reflect the opposite value of "cas.logout.remove-descendant-tickets", which should result in access-token and refresh-token not being removed when the linked TicketGrantingTicket is removed.

### CODE REVIEW

**Comment by mmoayyed** [comment]
Thank you for the tests. Please remove all code (Java) changes from the pull request, to demonstrate the issue.

**Comment by ThomasSeliger** [comment]
A happy new year to you all. I've had a long holiday break so it took me some time to get back on this topic. Thanks for the feedback @mmoayyed, I removed my code changes to demonstrate the issue

**Comment by mmoayyed** [comment]
Happy holidays! Thank you for the follow up. I don't know if I have any time left this week to review this, but I will surely circle back and review at some point. Thanks again!

**Comment by mmoayyed** [comment]
Hello, I had some time to review this pull request today; This pull request does not reproduce a problem, and the puppeteer tests all pass correctly. Furthermore, it seems inconsistent because the description says " failing cascade removals of oauth tokens in case the property cas.logout.remove-descendant-tickets is set to false" and then in tests this property is set to true. I am not sure which statement is correct here. Please revisit, update tests and follow up when you have made corrections. Thank you!

**Pull request closed without merging**
