### PR TITLE
Remove setters

### PR DESCRIPTION
**Pull request by DavidRG13**
Part of #2184

Remove come setters from core modules:

- authentication

### CODE REVIEW

**Comment by DavidRG13** [comment]
Same error than the other PR, please review this carefully as it's the authentication module

**Comment by mmoayyed** [comment]
Merge with master once more. Should be solved now.

**Comment by DavidRG13** [comment]
@mmoayyed, could you please give me a hand here? Looks like an easy one, but I know nothing about certificates

**Comment by mmoayyed** [comment]
I'll let Travis run this once more. You may want to run tests locally as well; given master builds fine I am inclined to think the breakage here is due to the changes you have made.

**Comment by mmoayyed** [comment]
Of course here is the breaking test as you noted:

```bash
org.apereo.cas.adaptors.x509.authentication.handler.support.X509CredentialsAuthenticationHandlerTests > verifyAuthenticate[5] FAILED
    java.lang.AssertionError: Authentication failed when it should have succeeded: Certificate keyUsage constraint forbids SSL client authentication.
        at org.junit.Assert.fail(Assert.java:88)
        at org.apereo.cas.adaptors.x509.authentication.handler.support.X509CredentialsAuthenticationHandlerTests.verifyAuthenticate(X509CredentialsAuthenticationHandlerTests.java:242)
```

First, verify that it indeed breaks locally as well. It should.
Second, run the test and observe the failing point. Then switch to master and run the test again. Note the delta between the tests and you'll find the breaking change.

**Comment by mmoayyed** [comment]
hey @DavidRG13 have you had a chance to review and resume work on this? Seems just about done :)

**Comment by DavidRG13** [comment]
Hi @mmoayyed, unfortonately not. Given all this conflicts, I guess it's worthy doing it from scratch again. I'll try to find some time this week and finish this

**Comment by mmoayyed** [comment]
OK. No problem; it's sad to see progress go to waste, but seems like restarting this would be the best approach. Focus on smaller changesets so they can be merged very quickly. 

And as always, thanks a bunch! I'll get this closed right now so we can begin anew.

**Pull request closed without merging**
