### PR TITLE
Closes #2549 Allow container datasource to be used directly or proxied

### LINKED ISSUE #2549: Hikari pool not correctly initialized for JNDI datasources
Version: cas-5.1.0-RC4-SNAPSHOT

I was glad to see the new dataSourceName configuration option in AbstractJpaProperties, so I changed my configuration immediately to be able to use a single datasource for all database actions (instead of separate datasources for service registry, ticket registry, mfa-gauth, audit etc.).

Unfortunately, Hikari pooling doesn't seem to play nice with my datasource and I get lots of errors complaining that the connection is already closed or that a connection can't be retrieved.
The most likely culprit here is that none of the Hikari pooling attributes are initialized by Beans.newDataSource when a dataSourceName is specified.

Do we really need Hikari for pooling when using JNDI datasources? If not, then could the following change be applied to org.apereo.cas.configuration.support.Beans?

```java
	/**
	 * Get new data source, from JNDI lookup or created via direct configuration of Hikari pool. If jpaProperties contains dataSourceName a lookup will be attempted If datasource not found via JNDI it
	 * will be
	 *
	 * @param jpaProperties the jpa properties
	 * @return the data source
	 */
	public static DataSource newDataSource(final AbstractJpaProperties jpaProperties) {
		final String dataSourceName = jpaProperties.getDataSourceName();
		if (StringUtils.isNotBlank(dataSourceName)) {
			try {
				final JndiDataSourceLookup dsLookup = new JndiDataSourceLookup();
				/*
				 * if user wants to do lookup as resource, they may include java:/comp/env in dataSourceName and put resource reference in web.xml otherwise dataSourceName is used as JNDI name
				 */
				dsLookup.setResourceRef(false);
				final DataSource containerDataSource = dsLookup.getDataSource(dataSourceName);
				/// --> Return the JNDI datasource instead of using Hikari
				return containerDataSource;
			} catch (final DataSourceLookupFailureException e) {
				LOGGER.warn("Lookup of datasource [{}] failed due to {} " + "falling back to configuration via JPA properties.", dataSourceName, e.getMessage());
			}
		}

		try {
			/// --> Moved down
			final HikariDataSource bean = new HikariDataSource();
			if (StringUtils.isNotBlank(jpaProperties.getDriverClass())) {
				bean.setDriverClassName(jpaProperties.getDriverClass());
			}
			bean.setJdbcUrl(jpaProperties.getUrl());
			bean.setUsername(jpaProperties.getUser());
			bean.setPassword(jpaProperties.getPassword());

			bean.setMaximumPoolSize(jpaProperties.getPool().getMaxSize());
			bean.setMinimumIdle(jpaProperties.getPool().getMinSize());
			bean.setIdleTimeout(jpaProperties.getIdleTimeout());
			bean.setLeakDetectionThreshold(jpaProperties.getLeakThreshold());
			bean.setInitializationFailTimeout(jpaProperties.isFailFast() ? 1 : 0);
			bean.setIsolateInternalQueries(jpaProperties.isIsolateInternalQueries());
			bean.setConnectionTestQuery(jpaProperties.getHealthQuery());
			bean.setAllowPoolSuspension(jpaProperties.getPool().isSuspension());
			bean.setAutoCommit(jpaProperties.isAutocommit());
			bean.setLoginTimeout(Long.valueOf(jpaProperties.getPool().getMaxWait()).intValue());
			bean.setValidationTimeout(jpaProperties.getPool().getTimeoutMillis());
			return bean;
		} catch (final Exception e) {
			LOGGER.error("Error creating DataSource: [{}]", e.getMessage());
			throw new IllegalArgumentException(e);
		}
	}

```

### PR DESCRIPTION
**Pull request by hdeadman**
Closes #2549

By proxying the datasource with a class loaded by the app classloader, it resolves some classloading issues, but now by default it won't proxy the datasource. Tomcat currently requires the proxy option to be turned on. 

This may be tricking Hikari into thinking it is delegating to an existing Hikari datasource but it is really a non-Hikari datasource. Might be better to just add a small datasource proxy class rather than using Hikari in a way it probably doesn't intend for people to use it. Since I am creating the datasource with a HikariConfig object, the HikariDataSource sets a fastPathPool instance variable and when getConnection is called it just delegates to that (the non-hikari container datasource). 

I didn't document this yet, but it adds one new configuration property that is false by default. You can wait to merge until later.

When I actually tried to set properties on the Hikari pool, making it a pool of a pool, I got an error like this:
```
Caused by: org.postgresql.util.PSQLException: Cannot change transaction read-only property in the middle of a transaction.
	at org.postgresql.jdbc2.AbstractJdbc2Connection.setReadOnly(AbstractJdbc2Connection.java:749) ~[postgresql-9.4-1203-jdbc42.jar:9.4]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126) ~[tomcat-jdbc.jar:?]
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108) ~[tomcat-jdbc.jar:?]
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81) ~[tomcat-jdbc.jar:?]
	at com.sun.proxy.$Proxy110.setReadOnly(Unknown Source) ~[?:?]
	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:400) ~[HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:361) ~[HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:199) ~[HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:444) ~[HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.access$200(HikariPool.java:71) ~[HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:631) ~[HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:617) ~[HikariCP-2.6.1.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_111]
	... 1 more
```

### CODE REVIEW

**Comment by hdeadman** [comment]
Ignore what I said about Hikari just delegating to the container datasource, I misread the code, it is still creating some sort of pool around the underlying datasource, I think. Hikari is using javassist to proxy the connections. If we did make a non-pooling datasource instead of using hikari, we could probably use their ProxyFactory class, but that can wait until someone observes a problem with the Hikari proxied datasource that they can't get around by using the non-proxied version.

**Comment by hdeadman** [comment]
Hold off on merging this for a bit. It probably fixes the reported issue and is no worse than what was there previously but I still have concerns about hikari pooling a pool. I just tried a fix that seems to work and doesn't do that.

**Comment by mmoayyed** [comment]
Sure. Keep the PR updated please, as always...and no rush, we have plenty of time left until the final GA.

**Comment by hdeadman** [comment]
I think the DataSourceProxy I added should avoid problems of having a pool wrapping a pool. If you have  a hikari pool that doesn't test connections then they could go bad and hikari won't know. You could also have situations where container pool is testing connections in background and closing them without hikari knowing or closing them for being idle without hikari knowing. Or maybe since hikari would be holding on to connections for a long time the underlying pool might think they were leaked and close them. The potential problems really boggle the mind. If you have to configure things like validation queries then it sort of defeats part of the purpose of using a single container datasource.  

One other note, if the Beans.java class were a spring ApplicationContextAware bean it would be easy to check for a datasource spring bean using  the dataSourceName and fall back to a JNDI lookup if the bean wasn't found. That would allow someone to define a datasource in Spring and share it across different cas modules without having to know the CAS bean names for each datasource. That can wait until someone needs it.

**Comment by mmoayyed** [comment]
Thanks, as always. I'll try to take a pass tomorrow. 

> One other note, if the Beans.java class were a spring ApplicationContextAware bean it would be easy to check for a datasource spring bean using the dataSourceName and fall back to a JNDI lookup if the bean wasn't found. 

There is a workaround for this, where you should be able to use `ApplicationContextProvider.getApplicationContext()` to get by. Might come in handy.

**Comment by mmoayyed** [comment]
Reviewed. All good.

**Pull request merged**
