### PR TITLE
Delegated authentication: fix again the DistributedJ2ESessionStore

### PR DESCRIPTION
**Pull request by leleuj**
This is a new implementation of the `DistributedJ2ESessionStore` based on a cookie to solve previous issues.

### CODE REVIEW

**Comment by leleuj** [comment]
@jgribonvald This is ready to be merged for the v6.1.3 release. Can you quickly confirm this fixes your issue too? Thanks

**Comment by mmoayyed** [comment]
I dont think we are going to much feedback, specially in leu of the holidays this week. Given the release date coming in, I think it would be best to merge this for now and review later once folks have had a chance to test it. WDYT?

**Comment by leleuj** [comment]
Yes, I'm in line. I'm very confident on this, it has been tested several times. Merging...

**Comment by jgribonvald** [comment]
This is working ! Thanks for the fix!

**Pull request merged**
