### PR TITLE
remove span and place th:if condition in inner section

### PR DESCRIPTION
**Pull request by rbonatuvic**
- [x] Brief description of changes applied
- [] Test cases for all modified changes, where applicable
- [] The same pull request targeted at the master branch, if applicable
- [] Any documentation on how to configure, test
- [] Any possible limitations, side effects, etc
- [] Reference any other pull requests that might be related

Description:
Conditional logic moved from span tag to inner section tag, span tag removed.

### CODE REVIEW

**Comment by rbonatuvic** [comment]
There is already a test in the project.
Should I have marked the box as included?
This is a trivial change with no functional change.
Please reopen.

**Comment by mmoayyed** [comment]
Why are you making this change?

**Comment by mmoayyed** [comment]
> There is already a test in the project.

Also please identify which puppeteer tests you have run already to ensure the changes you made here do not break tests.

**Comment by mmoayyed** [comment]
Thank you for the notes.

The tests you are running have nothing to do with the changes you made. They are testing "code", you have modified "html". We have puppeteer tests that run browser tests and verify page elements, etc. Please examine those.

**Comment by rbonatuvic** [comment]
I ran all the tests in Functional Tests job on github. All the ones that reference 'delegate' or 'wsfed' passed (the conditional statements I modified reference variables with delegate or wsfed in the name).
[https://github.com/rbonatuvic/cas/actions/runs/11695614126](https://github.com/rbonatuvic/cas/actions/runs/11695614126)
The only failing tests also failed in the matching master branch; and appear to be unrelated to the change I made.

**Comment by mmoayyed** [comment]
Thank you very much for the details.

**Pull request merged**
