### PR TITLE
Before creating mongo indexes delete any index with the same key but different options

### PR DESCRIPTION
**Pull request by sbearcsiro**
Without a change like this, changing a ticket timeout will cause an Exception on startup unless the index based on the timeout is removed manually.

### CODE REVIEW

**Comment by mmoayyed** [comment]
```
> Task :support:cas-server-support-mongo-ticket-registry:checkstyleMain FAILED
[ant:checkstyle] [ERROR] /home/travis/build/apereo/cas/support/cas-server-support-mongo-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/MongoDbTicketRegistry.java:42: Returning an unmodifiable collection is specially problematic for serialization tasks. To avoid future side effects try using an empty collection of size zero instead [collectionsUnmodifiable]
> Task :support:cas-server-support-mongo-service-registry:findbugsMain
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':support:cas-server-support-mongo-ticket-registry:checkstyleMain'.
> Checkstyle rule violations were found. See the report at: file:///home/travis/build/apereo/cas/support/cas-server-support-mongo-ticket-registry/build/reports/checkstyle/main.html
  Checkstyle files with violations: 1
  Checkstyle violations by severity: [error:1]

```

**Comment by sbearcsiro** [comment]
FWIW that checkstyle rule that failed probably shouldn't apply to static fields since they shouldn't be serialised.

**Comment by mmoayyed** [comment]
You may want to reconsider using CollectionUtils to get around the styling issue, and if you could merge with master as well and resolve conflicts, I think this is GTG. 

Thank you, as always.

**Comment by sbearcsiro** [comment]
It looks like the mongo types have changed due to an updated mongo driver and / or spring mongo, I'll close this one and resubmit separately for 5.3.x and master

**Pull request closed without merging**
