### PR TITLE
Hazelcast: update hearbeat interval to 300 seconds. 

### LINKED ISSUE #1818: Hazelcast max.no.heartbeats matches heartbeat interval
We recently ran into issues that after a period of time ClusterHeartbeatManager in Hazelcast would remove a functioning cluster node because it thought it had become non-responsive.  Log files show the node functioning properly up until it was removed by the master.

We traced the cause of the behavior down to the setting of max.no.heartbeats in CAS to 5 seconds.  Unfortunately the Hazelcast heartbeat interval is set to 5 seconds in com.hazelcast.instance.GroupProperty

HEARTBEAT_INTERVAL_SECONDS("hazelcast.heartbeat.interval.seconds", 5, SECONDS)

This is different than the 1 second interval that specified in the online Hazelcast documentation.

Setting the max.no.heartbeat in CAS to the default of 300 specified by Hazelcast cleared the issue for us.

### PR DESCRIPTION
**Pull request by tsschmi**
Closes #1818

Set the default max.no.hearbeat for Hazelcast to 300 seconds

### CODE REVIEW

**Comment by mmoayyed** [comment]
Cool. You probably should also update the docs.

And have you signed the ICLA? I forget.

**Comment by tsschmi** [comment]
No, I have not signed the ICLA, this the first pull request I sent

**Comment by mmoayyed** [comment]
OK. Could I ask you to get the fom from here and then submit it via email?
https://www.apereo.org/licensing/agreements

Let me know when you have. PR looks great.

**Comment by mmoayyed** [comment]
Or, you could alternatively use this:
https://www.apereo.org/licensing/agreements/icla

**Comment by mmoayyed** [comment]
Status check: @tsschmi were you able to sign the doc?

**Comment by tsschmi** [comment]
I am in a fairly new position.  It is unclear if I am able to sign the
release on my own for work done with university resources and time.  We
have sent it up the chain and have not heard back yet.  You may want to
cancel the pull and make the change yourself, since it is quite small.  We
intend to get the release signed and filed so that we can contribute back
larger changes in the future.

Sorry for the delay.

**Comment by mmoayyed** [comment]
Thanks. I'll give it a few more days, and then will probably will take up your suggestion and make the change.

**Comment by mmoayyed** [comment]
Merged out of band via https://github.com/apereo/cas/commit/5f6dc4eef052322e4562a541f5d8be9ab9282187

**Pull request closed without merging**
