### PR TITLE
Mgmt app first draft

### PR DESCRIPTION
**Pull request by mmoayyed**
Updates the management app with new fields that v5 adds to the CAS service model:

1. Support for SAML clients
2. Support MFA
3. Support for CAS props
4. Support for a few other access strategies

This is still a first draft that simply focuses on the UI elements. Nothing is yet wired up yet and likely will be done in M2.

### CODE REVIEW

**Comment by dima767** [comment]
Looks good to me :)

**Comment by mmoayyed** [comment]
image

**Comment by mmoayyed** [comment]
image

**Comment by mmoayyed** [comment]
image

**Comment by mmoayyed** [comment]
image

**Pull request merged**
