### PR TITLE
Convert Tomcat config from overriding the factory bean to providing a customizer

### PR DESCRIPTION
**Pull request by sbearcsiro**
This PR converts `CasEmbeddedContainerTomcatConfiguration` to use a `EmbeddedServletContainerCustomizer` instead of providing a `TomcatEmbeddedServletContainerFactory` so that CAS implementations can override the factory themselves (eg to enable JNDI) whilst also benefitting from the CAS tomcat configuration properties.

### CODE REVIEW

**Comment by mmoayyed** [comment]
I have had to switch this back in order to get access to the underlying Tomcat engine. I think you should still be able to override the factory bean since it's made conditional. If this poses an issue, please post back.

**Comment by sbearcsiro** [comment]
Looks good - it might be worth extracting the anonymous class into a `CasTomcatContainerFactory` or similar class so that implementations that wish to override the `TomcatContainerFactory` can use it as a base / delegate to it?

**Comment by mmoayyed** [comment]
Sound great! Is this something you prefer me to do, or would you be interested in doing that yourself in a patch?

**Comment by sbearcsiro** [comment]
I'm happy to submit a patch

**Pull request merged**
