### PR TITLE
Fix MUST_CHANGE_PASSWORD state breaking when pm is enabled

### PR DESCRIPTION
**Pull request by marwatk**
The view CasWebflowConstants.VIEW_ID_MUST_CHANGE_PASSWORD (casMustChangePassView) isn't being registered if pm was enabled. 

If an authentication method results in an AccountPasswordMustChangeException an error is thrown instead of starting the password management flow.

The resulting error looked like this:

```
2017-09-20 14:24:14,396 DEBUG [org.apereo.cas.authentication.support.DefaultAccountStateHandler] - <Handling error [CHANGE_AFTER_RESET]>
2017-09-20 14:24:14,396 DEBUG [org.apereo.cas.authentication.PolicyBasedAuthenticationManager] - <[LdapAuthenticationHandler] exception details: [null].>
2017-09-20 14:24:14,397 ERROR [org.apereo.cas.authentication.PolicyBasedAuthenticationManager] - <Authentication has failed. Credentials may be incorrect or CAS cannot find authentication handler that supports [mwatkins@test.org] of type [UsernamePasswordCredential].>
2017-09-20 14:24:14,398 INFO [org.apereo.inspektr.audit.support.Slf4jLoggingAuditTrailManager] - <Audit trail record BEGIN
=============================================================
WHO: mwatkins@test.org
WHAT: Supplied credentials: [mwatkins@test.org]
ACTION: AUTHENTICATION_FAILED
APPLICATION: CAS
WHEN: Wed Sep 20 14:24:14 MDT 2017
CLIENT IP ADDRESS: 127.0.0.1
SERVER IP ADDRESS: 127.0.0.1
=============================================================

>
2017-09-20 14:24:14,399 DEBUG [org.apereo.cas.web.flow.resolver.impl.InitialAuthenticationAttemptWebflowEventResolver] - <1 errors, 0 successes>
org.apereo.cas.authentication.AuthenticationException: 1 errors, 0 successes
	at org.apereo.cas.authentication.PolicyBasedAuthenticationManager.evaluateFinalAuthentication(PolicyBasedAuthenticationManager.java:401) ~[cas-server-core-authentication-5.2.0-RC4-SNAPSHOT.jar!/:5.2.0-RC4-SNAPSHOT]
	at org.apereo.cas.authentication.PolicyBasedAuthenticationManager.authenticateInternal(PolicyBasedAuthenticationManager.java:381) ~[cas-server-core-authentication-5.2.0-RC4-SNAPSHOT.jar!/:5.2.0-RC4-SNAPSHOT]
	at org.apereo.cas.authentication.PolicyBasedAuthenticationManager.authenticate(PolicyBasedAuthenticationManager.java:221) ~[cas-server-core-authentication-5.2.0-RC4-SNAPSHOT.jar!/:5.2.0-RC4-SNAPSHOT]
	at org.apereo.cas.authentication.PolicyBasedAuthenticationManager$$FastClassBySpringCGLIB$$90e801d3.invoke(<generated>) ~[cas-server-core-authentication-5.2.0-RC4-SNAPSHOT.jar!/:5.2.0-RC4-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738) ~[spring-aop-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85) ~[spring-aop-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.apereo.inspektr.audit.AuditTrailManagementAspect.handleAuditTrail(AuditTrailManagementAspect.java:134) ~[inspektr-audit-1.7.GA.jar!/:1.7.GA]
	…
2017-09-20 14:24:14,399 DEBUG [org.apereo.cas.web.flow.resolver.impl.AbstractCasWebflowEventResolver] - <Resolved single event [authenticationFailure] via [org.apereo.cas.web.flow.resolver.impl.InitialAuthenticationAttemptWebflowEventResolver] for this context>
2017-09-20 14:24:14,400 DEBUG [org.apereo.cas.web.flow.AuthenticationExceptionHandlerAction] - <Located current event [authenticationFailure]>
2017-09-20 14:24:14,400 DEBUG [org.apereo.cas.web.flow.AuthenticationExceptionHandlerAction] - <Located error attribute [class org.apereo.cas.authentication.AuthenticationException] with message [1 errors, 0 successes] from the current event>
2017-09-20 14:24:14,400 DEBUG [org.apereo.cas.web.flow.AuthenticationExceptionHandlerAction] - <Final event id resolved from the error is [AccountPasswordMustChangeException]>
2017-09-20 14:24:14,431 DEBUG [org.apereo.cas.web.FlowExecutionExceptionResolver] - <Ignoring the received exception due to a type mismatch>
org.springframework.webflow.execution.FlowExecutionException: Exception thrown in state 'handleAuthenticationFailure' of flow 'login'
	at org.springframework.webflow.engine.impl.FlowExecutionImpl.wrap(FlowExecutionImpl.java:573) ~[spring-webflow-2.4.6.RELEASE.jar!/:2.4.6.RELEASE]
	at org.springframework.webflow.engine.impl.FlowExecutionImpl.resume(FlowExecutionImpl.java:263) ~[spring-webflow-2.4.6.RELEASE.jar!/:2.4.6.RELEASE]
	at org.springframework.webflow.executor.FlowExecutorImpl.resumeExecution(FlowExecutorImpl.java:169) ~[spring-webflow-2.4.6.RELEASE.jar!/:2.4.6.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
…
Caused by: java.lang.IllegalArgumentException: Cannot find state with id 'casMustChangePassView' in flow 'login' -- Known state ids are 'array<String>['initialAuthenticationRequestValidationCheck', 'ticketGrantingTicketCheck', 'initializeLoginForm', 'viewLoginForm', 'realSubmit', 'showAuthenticationWarningMessages', 'sendTicketGrantingTicket', 'viewRedirectToUnauthorizedUrlView', 'viewServiceErrorView', 'redirectView', 'postView', 'headerView', 'viewGenericLoginSuccess', 'showWarningView', 'finalizeWarning', 'serviceUnauthorizedCheck', 'serviceCheck', 'warn', 'gatewayRequestCheck', 'hasServiceCheck', 'renewRequestCheck', 'generateServiceTicket', 'terminateSession', 'gatewayServicesManagementCheck', 'serviceAuthorizationCheck', 'redirect', 'handleAuthenticationFailure', 'myAccessAuthenticationCheck', 'casAuthenticationBlockedView', 'casBadWorkstationView', 'casBadHoursView', 'casAccountLockedView', 'casAccountDisabledView', 'casPasswordUpdateSuccess', 'passwordChangeAction', 'casExpiredPassView', 'casResetPasswordSendInstructionsView', 'sendInstructions', 'casResetPasswordSentInstructionsView']'
	at org.springframework.webflow.engine.Flow.getStateInstance(Flow.java:342) ~[spring-webflow-2.4.6.RELEASE.jar!/:2.4.6.RELEASE]
	at org.springframework.webflow.engine.support.DefaultTargetStateResolver.resolveTargetState(DefaultTargetStateResolver.java:60) ~[spring-webflow-2.4.6.RELEASE.jar!/:2.4.6.RELEASE]
	at org.springframework.webflow.engine.Transition.execute(Transition.java:218) ~[spring-webflow-2.4.6.RELEASE.jar!/:2.4.6.RELEASE]
	at org.springframework.webflow.engine.impl.FlowExecutionImpl.execute(FlowExecutionImpl.java:395) ~[spring-webflow-2.4.6.RELEASE.jar!/:2.4.6.RELEASE]
	... 83 more
2017-09-20 14:24:14,431 DEBUG [org.apereo.cas.web.FlowExecutionExceptionResolver] - <Ignoring the received exception due to a type mismatch>
org.springframework.webflow.execution.FlowExecutionException: Exception thrown in state 'handleAuthenticationFailure' of flow 'login'
	at org.springframework.webflow.engine.impl.FlowExecutionImpl.wrap(FlowExecutionImpl.java:573) ~[spring-webflow-2.4.6.RELEASE.jar!/:2.4.6.RELEASE]
	at org.springframework.webflow.engine.impl.FlowExecutionImpl.resume(FlowExecutionImpl.java:263) ~[spring-webflow-2.4.6.RELEASE.jar!/:2.4.6.RELEASE]
	at org.springframework.webflow.executor.FlowExecutorImpl.resumeExecution(FlowExecutorImpl.java:169) ~[spring-webflow-2.4.6.RELEASE.jar!/:2.4.6.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
…
Caused by: java.lang.IllegalArgumentException: Cannot find state with id 'casMustChangePassView' in flow 'login' -- Known state ids are 'array<String>['initialAuthenticationRequestValidationCheck', 'ticketGrantingTicketCheck', 'initializeLoginForm', 'viewLoginForm', 'realSubmit', 'showAuthenticationWarningMessages', 'sendTicketGrantingTicket', 'viewRedirectToUnauthorizedUrlView', 'viewServiceErrorView', 'redirectView', 'postView', 'headerView', 'viewGenericLoginSuccess', 'showWarningView', 'finalizeWarning', 'serviceUnauthorizedCheck', 'serviceCheck', 'warn', 'gatewayRequestCheck', 'hasServiceCheck', 'renewRequestCheck', 'generateServiceTicket', 'terminateSession', 'gatewayServicesManagementCheck', 'serviceAuthorizationCheck', 'redirect', 'handleAuthenticationFailure', 'myAccessAuthenticationCheck', 'casAuthenticationBlockedView', 'casBadWorkstationView', 'casBadHoursView', 'casAccountLockedView', 'casAccountDisabledView', 'casPasswordUpdateSuccess', 'passwordChangeAction', 'casExpiredPassView', 'casResetPasswordSendInstructionsView', 'sendInstructions', 'casResetPasswordSentInstructionsView']'
	at org.springframework.webflow.engine.Flow.getStateInstance(Flow.java:342) ~[spring-webflow-2.4.6.RELEASE.jar!/:2.4.6.RELEASE]
	at org.springframework.webflow.engine.support.DefaultTargetStateResolver.resolveTargetState(DefaultTargetStateResolver.java:60) ~[spring-webflow-2.4.6.RELEASE.jar!/:2.4.6.RELEASE]
	at org.springframework.webflow.engine.Transition.execute(Transition.java:218) ~[spring-webflow-2.4.6.RELEASE.jar!/:2.4.6.RELEASE]
	... 83 more
2017-09-20 14:24:14,444 DEBUG [org.springframework.boot.web.filter.OrderedRequestContextFilter] - <Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@7abf87b6>
2017-09-20 14:24:17,460 ERROR [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/portal-cas].[dispatcherServlet]] - <Servlet.service() for servlet [dispatcherServlet] in context with path [/portal-cas] threw exception [Request processing failed; nested exception is org.springframework.webflow.execution.FlowExecutionException: Exception thrown in state 'handleAuthenticationFailure' of flow 'login'] with root cause>
java.lang.IllegalArgumentException: Cannot find state with id 'casMustChangePassView' in flow 'login' -- Known state ids are 'array<String>['initialAuthenticationRequestValidationCheck', 'ticketGrantingTicketCheck', 'initializeLoginForm', 'viewLoginForm', 'realSubmit', 'showAuthenticationWarningMessages', 'sendTicketGrantingTicket', 'viewRedirectToUnauthorizedUrlView', 'viewServiceErrorView', 'redirectView', 'postView', 'headerView', 'viewGenericLoginSuccess', 'showWarningView', 'finalizeWarning', 'serviceUnauthorizedCheck', 'serviceCheck', 'warn', 'gatewayRequestCheck', 'hasServiceCheck', 'renewRequestCheck', 'generateServiceTicket', 'terminateSession', 'gatewayServicesManagementCheck', 'serviceAuthorizationCheck', 'redirect', 'handleAuthenticationFailure', 'myAccessAuthenticationCheck', 'casAuthenticationBlockedView', 'casBadWorkstationView', 'casBadHoursView', 'casAccountLockedView', 'casAccountDisabledView', 'casPasswordUpdateSuccess', 'passwordChangeAction', 'casExpiredPassView', 'casResetPasswordSendInstructionsView', 'sendInstructions', 'casResetPasswordSentInstructionsView']'
	at org.springframework.webflow.engine.Flow.getStateInstance(Flow.java:342) ~[spring-webflow-2.4.6.RELEASE.jar!/:2.4.6.RELEASE]
	at org.springframework.webflow.engine.support.DefaultTargetStateResolver.resolveTargetState(DefaultTargetStateResolver.java:60) ~[spring-webflow-2.4.6.RELEASE.jar!/:2.4.6.RELEASE]
	at org.springframework.webflow.engine.Transition.execute(Transition.java:218) ~[spring-webflow-2.4.6.RELEASE.jar!/:2.4.6.RELEASE]
	at org.springframework.webflow.engine.impl.FlowExecutionImpl.execute(FlowExecutionImpl.java:395) ~[spring-webflow-2.4.6.RELEASE.jar!/:2.4.6.RELEASE]
	at org.springframework.webflow.engine.impl.RequestControlContextImpl.execute(RequestControlContextImpl.java:214) ~[spring-webflow-2.4.6.RELEASE.jar!/:2.4.6.RELEASE]
```

### CODE REVIEW

**Comment by mmoayyed** [comment]
Ported back to 5.1.x. Thanks again

**Comment by fazla043264** [comment]
this is the log
=============================================================
WHO: audit:unknown
WHAT: [event=success,timestamp=Mon Nov 26 14:08:04 MYT 2018,source=RankedMultifactorAuthenticationProviderWebflowEventResolver]
ACTION: AUTHENTICATION_EVENT_TRIGGERED
APPLICATION: CAS
WHEN: Mon Nov 26 14:08:04 MYT 2018
CLIENT IP ADDRESS: 0:0:0:0:0:0:0:1
SERVER IP ADDRESS: 0:0:0:0:0:0:0:1
=============================================================

>
2018-11-26 14:08:15,432 DEBUG [org.apereo.cas.web.view.CasReloadableMessageBundle] - <No properties file found for [classpath:custom_messages_en] - neither plain properties nor XML>
2018-11-26 14:08:15,440 DEBUG [org.apereo.cas.web.view.CasReloadableMessageBundle] - <No properties file found for [classpath:custom_messages] - neither plain properties nor XML>
2018-11-26 14:08:15,447 DEBUG [org.apereo.cas.web.view.CasReloadableMessageBundle] - <No properties file found for [classpath:messages_en] - neither plain properties nor XML>
2018-11-26 14:08:15,448 DEBUG [org.apereo.cas.web.view.CasReloadableMessageBundle] - <Loading properties [messages.properties] with encoding 'UTF-8'>
Hibernate:
    select
        abstractre0_.id as id2_0_,
        abstractre0_.access_strategy as access_s3_0_,
        abstractre0_.attribute_release as attribut4_0_,
        abstractre0_.description as descript5_0_,
        abstractre0_.evaluation_order as evaluati6_0_,
        abstractre0_.expiration_policy as expirati7_0_,
        abstractre0_.informationUrl as informat8_0_,
        abstractre0_.logo as logo9_0_,
        abstractre0_.logout_type as logout_10_0_,
        abstractre0_.logout_url as logout_11_0_,
        abstractre0_.mfa_policy as mfa_pol12_0_,
        abstractre0_.name as name13_0_,
        abstractre0_.privacyUrl as privacy14_0_,
        abstractre0_.proxy_policy as proxy_p15_0_,
        abstractre0_.public_key as public_16_0_,
        abstractre0_.required_handlers as require17_0_,
        abstractre0_.responseType as respons18_0_,
        abstractre0_.serviceId as service19_0_,
        abstractre0_.theme as theme20_0_,
        abstractre0_.username_attr as usernam21_0_,
        abstractre0_.assertionAudiences as asserti22_0_,
        abstractre0_.encryptAssertions as encrypt23_0_,
        abstractre0_.encryptAttributes as encrypt24_0_,
        abstractre0_.encryptable_attrs as encrypt25_0_,
        abstractre0_.metadataCriteriaDirection as metadat26_0_,
        abstractre0_.metadataCriteriaPattern as metadat27_0_,
        abstractre0_.mdCriteriaRmEmptyEntities as mdCrite28_0_,
        abstractre0_.mdCriteriaRmRolelessEntities as mdCrite29_0_,
        abstractre0_.metadataCriteriaRoles as metadat30_0_,
        abstractre0_.metadataExpirationDuration as metadat31_0_,
        abstractre0_.metadataLocation as metadat32_0_,
        abstractre0_.metadataMaxValidity as metadat33_0_,
        abstractre0_.metadataSignatureLocation as metadat34_0_,
        abstractre0_.nameIdQualifier as nameIdQ35_0_,
        abstractre0_.reqAuthnContextClass as reqAuth36_0_,
        abstractre0_.requiredNameIdFormat as require37_0_,
        abstractre0_.spNameIdQualifier as spNameI38_0_,
        abstractre0_.signAssertions as signAss39_0_,
        abstractre0_.signResponses as signRes40_0_,
        abstractre0_.signingCredentialType as signing41_0_,
        abstractre0_.skipGenAssertionNameId as skipGen42_0_,
        abstractre0_.skipGenSubConfInRespTo as skipGen43_0_,
        abstractre0_.skipGenSubConfNameId as skipGen44_0_,
        abstractre0_.skipGenSubConfNotBefore as skipGen45_0_,
        abstractre0_.skipGenSubConNotOnOrAfter as skipGen46_0_,
        abstractre0_.skipGenSubConRecipient as skipGen47_0_,
        abstractre0_.expression_type as expressi1_0_
    from
        RegexRegisteredService abstractre0_
2018-11-26 14:08:24,227 INFO [org.apereo.cas.services.AbstractServicesManager] - <Loaded [1] service(s) from [JpaServiceRegistry].>
2018-11-26 14:08:34,206 INFO [org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner] - <[0] expired tickets removed.>
2018-11-26 14:08:49,306 WARN [com.zaxxer.hikari.HikariConfig] - <HikariPool-3 - idleTimeout is close to or more than maxLifetime, disabling it.>
2018-11-26 14:08:49,306 WARN [com.zaxxer.hikari.HikariConfig] - <HikariPool-3 - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.>
2018-11-26 14:09:04,065 WARN [org.apereo.cas.util.io.CommunicationsManager] - <CAS is unable to send sms messages given no settings are defined to account for sms providers, etc>
2018-11-26 14:09:04,068 ERROR [org.apereo.cas.pm.web.flow.actions.SendForgotUsernameInstructionsAction] - <No email is provided>
2018-11-26 14:09:04,102 WARN [org.apereo.cas.web.view.CasReloadableMessageBundle] - <The code [No email is provided.] cannot be found in the default language bundle and will be used as the message itself.>
Hibernat

**Comment by marwatk** [comment]
Is that log from CAS 6 when attempting a normal password reset? If so I'm seeing similar behavior with our migration, too. (Password resets unable to find user or email). I'm going to take a look today and see what I can find.

**Comment by marwatk** [comment]
I think I found the problem. [These two variables](https://github.com/apereo/cas/blob/master/support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/PasswordManagementWebflowConfigurer.java#L45-L46) both have the same value. I think this clobbers the password reset flow in favor of the forgot username flow. Switching one of the values (or both, to be less generic) should fix it.

I'll have to set up a build environment to test the change and submit a pull request, may take a couple of days. Unless you want to take a look at it, @mmoayyed?

**Comment by fazla043264** [comment]
Yes that is the log of CAS 6. @marwatk. In both the prerelease CAS 6.0.3 and CAS 6.0.4

**Pull request merged**
