### PR TITLE
Use a hard timeout for the multi use policy

### PR DESCRIPTION
**Pull request by leleuj**
Following up https://github.com/apereo/cas/pull/5505

The `MultiTimeUseOrTimeoutExpirationPolicy` now uses a hard timeout.

BTW, the expiration test is revisited in `VerifyPasswordResetRequestAction`.

Waiting for the build to pass...

### CODE REVIEW

**Comment by mmoayyed** [comment]
@apereocas-bot runci

**Comment by leleuj** [comment]
Thanks. Should we backport it to the 6.5 branch?

**Comment by mmoayyed** [comment]
Yes, at least the change for the MultiTimeUseOrTimeoutExpirationPolicy should be backported. Deleting the token does not have to be backported, since that is a change in behavior and likely does not fit.

**Comment by leleuj** [comment]
No problem. See: https://github.com/apereo/cas/pull/5508

**Pull request merged**
