### PR TITLE
Allow successful/failed authn attempts into the stats page as a chart

### PR DESCRIPTION
**Pull request by mmoayyed**
Closes the last remaining item on https://github.com/apereo/cas/issues/2068

### CODE REVIEW

**Comment by mmoayyed** [comment]
@mindblender this looks like it's got changes that don't have anything to do with authn graphs. Do I have the right branch here?

**Comment by mmoayyed** [comment]
Specifically the Dashboard.js file: is that complete? If we merged this as is, is it going to break/remove the existing dashboard functionality?

**Comment by mindblender** [comment]
@mmoayyed No it would not cause any problems since the files are not referenced.  I wen ahead and removed them from this PR.

**Comment by mmoayyed** [comment]
Great. Thanks. I'll merge and resume testing a bit.

**Comment by mmoayyed** [comment]
When I build and deploy, I see `cas/js/statistics-bundle.js 404 ()` in the console. What do I need to do to build the JS bundle?

**Comment by mmoayyed** [comment]
Also it looks like webpack cannot build:

```
> Task :webapp:runWebpack
Hash: e4605ac23da5642e23a7
Version: webpack 2.1.0-beta.25
Time: 13964ms
               Asset    Size  Chunks             Chunk Names
statistics-bundle.js  696 kB       0  [emitted]  statistics
    + 1170 hidden modules

ERROR in Entry module not found: Error: Can't resolve './resources/static/js/components/dashboard/Dashboard' in '/Users/Misagh/Workspace/GitWorkspace/cas-server/webapp'


FAILURE: Build failed with an exception.

```

**Comment by mmoayyed** [comment]
Ended up removing a number of references to Dashboard. Now I can see this:

image

However, no graph is actually displayed (I know for certain the data is available). Clicking on refresh causes this:

```
statistics-bundle.js:19 Uncaught TypeError: this._listeners[t.type] is not a function
    at HTMLButtonElement._ (statistics-bundle.js:19)
```

**Comment by mmoayyed** [comment]
One last thing: I am not sure but I think `webapp/resources/static/js/statistics-bundle.js` should be added to gitignore?

**Pull request merged**
