### PR TITLE
WIP Update to pac4j-javaee v5.4

### PR DESCRIPTION
**Pull request by leleuj**
The `pac4j-jee` dependency is now deprecated in pac4j and the `pac4j-javaee` dependency must be used instead.

There is a package renaming: this breaking change won't happen again when upgrading to JakartaEE (`pac4j-jakartaee`).

### CODE REVIEW

**Comment by leleuj** [comment]
There are many files changed, but this is expected as the `org.pac4j.core` package has been renamed as `org.pac4j.jee` for several core components.

**Comment by mmoayyed** [comment]
@apereocas-bot runci

**Comment by mmoayyed** [comment]
Sorry about the noise. The bot should be behaving better now.

**Comment by leleuj** [comment]
No problem. We can remove the "WIP" title, it's a final work...

**Pull request merged**
