### PR TITLE
Add logout support for OIDC in authn delegation

### PR DESCRIPTION
**Pull request by leleuj**
After a delegated authentication at an OIDC provider, if this OIDC provider sends a logout request to the CAS server, the CAS server does not perform a CAS logout. It works for SAML though.

This PR fixes the problem and adds a test to confirm the behavior.

### CODE REVIEW

**Comment by leleuj** [comment]
I will investigate on failing tests.

**Comment by leleuj** [comment]
I think the `Publish documentation` issue is not related to my change.

**Comment by leleuj** [comment]
The `delegation` issue:

```java
Execution failed for task ':support:cas-server-support-pac4j-webflow:testDelegation'.
> Failure closing session
  Standard error from JVM:
      OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
```

does not seem to be related to my change either.

**Comment by leleuj** [comment]
Re-running failing tests to confirm the outcome...

**Comment by leleuj** [comment]
After re-running the failing tests, the SAML2 tests pass while the delegation tests still don't but I see the same issue on the master. Thus, I consider that this PR is not the culprit. Keep me posted if you need me to fix something in any case...

**Comment by mmoayyed** [comment]
Thank you, sure. I'll take a look shortly.

**Comment by mmoayyed** [comment]
This generally looks OK, thank you. I am in the process of moving OIDC/SAML2 functionality out of the main module for delegated authn, and when done, I'll also merge and include this changeset there in the final result. I am hoping to do this before the weekend.

**Comment by leleuj** [comment]
Good! Thanks

**Comment by mmoayyed** [comment]
This is merged into the master branch

**Pull request closed without merging**
