### PR TITLE
Fix the double renew call

### PR DESCRIPTION
**Pull request by leleuj**
Backport of: https://github.com/apereo/cas/pull/5640

master: https://github.com/apereo/cas/pull/5640

### CODE REVIEW

**Comment by leleuj** [comment]
@mmoayyed Given the postponed ETA of the final 7.0 release, I think we should still be able to functionally modify the 6.6.x stream.

**Comment by hdeadman** [comment]
I think the bot is complaining that there is no reference to a fix on master (port forward) - 

master: https://github.com/apereo/cas/pull/$PR_NUMBER

**Comment by hdeadman** [comment]
@leleuj sorry, i tried to re-open with my comment pointing to your master PR but it probably has to be edited into your message? In the following format probably:

```master: https://github.com/apereo/cas/pull/5640```

**Comment by hdeadman** [comment]
Apparently i can edit your message, so trying again.

**Comment by leleuj** [comment]
@hdeadman Good point! I thought the 6.6.x development was closed. I should have read better!

@mmoayyed If the 6.6.x stream still evolves, we should update: https://apereo.github.io/cas/developer/Maintenance-Policy.html#eol-schedule

**Comment by mmoayyed** [comment]
Sure. I did update the page.

**Pull request merged**
