### PR TITLE
[Doc typo fix] OAuth-Protocol.md

### PR DESCRIPTION
**Pull request by acidjames**
Doc links were pointing to html. Format is markdown (.md)

Closes #IssueNumber

Ensure that you include the following:

- [] Brief description of changes applied
- [] Any documentation on how to configure, test
- [] Any possible limitations, side effects, etc
- [] Reference any other pull requests that might be related.

### CODE REVIEW

**Comment by mmoayyed** [comment]
No they all need to be html. See the official docs.

**Comment by mmoayyed** [comment]
Thanks for the pull request though. A for effort :)

**Comment by acidjames** [comment]
Well i found that a bit confusing because i'm used to browsing docs on github and not on website :)

**Comment by mmoayyed** [comment]
Understood. You're rather adventurous though! Keep browsing. All improvements/suggestions to docs are extremely welcomed.

**Comment by acidjames** [comment]
Well thanks for your kind words @mmoayyed, and thanks for this app. We have been using it for more than 10 years at University of Toulouse, France. I'll be reading and probably be testing Oauth any time soon so if i find anything i'll be happy to contribute :)

**Comment by mmoayyed** [comment]
Excellent. Good for you. Team effort. Post back all findings, and better yet, more pull requests. Always happy to merge :)

**Pull request closed without merging**
