### PR TITLE
Replace org.reflections with ClassGraph

### PR DESCRIPTION
**Pull request by larsgrefer**
This replaces the old reflections library, which isnt very actively developed anymore with the more recent ClassGraph library.

Old: https://github.com/ronmamo/reflections
New: https://github.com/classgraph/classgraph

### CODE REVIEW

**Comment by larsgrefer** [comment]
@apereocas-bot Since this is a direct one-to-one replacement of an implementation detail, the existing tests should be sufficient to verify that the outside behavior is still working as expected.

If you have a suggestion about what kind of tests should be added, please re-open this as "Draft" so I can keep working on it.

**Comment by larsgrefer** [comment]
I've created the Utils class and added a test. How do we get GitHub to run the tests/checks?

**Comment by mmoayyed** [comment]
@apereocas-bot runci

**Comment by larsgrefer** [comment]
The checkstyle errors caused by my changes should now be fixed.

**Comment by mmoayyed** [comment]
Changes seem to be breaking tests. Please review.

**Comment by mmoayyed** [comment]
@apereocas-bot runci

**Pull request merged**
