### PR TITLE
doc: fix typo in theme_name variable

### PR DESCRIPTION
**Pull request by jgraglia**

### CODE REVIEW

**Comment by mmoayyed** [comment]
Thank you for the patch. This is not a typo; it's a placeholder reference for the actual theme name.

**Comment by jgraglia** [comment]
Hi, you are right it's a placeholder. But what I wanted to say is that this reference is noted
`theme_name` (with an underscore) in the 2 lines aboved, and that in this line it is `theme-name` with a - (dash)

```
cas.standard.css.file=/themes/[theme_name]/css/cas.css
cas.javascript.file=/themes/[theme_name]/js/cas.js
cas.admin.css.file=/themes/[theme-name]/css/admin.css
```

**Comment by mmoayyed** [comment]
Ah, excellent. My apologies for being careless here. Thank you.

**Comment by mmoayyed** [comment]
If you'd like to submit the same sort of change for the master branch, that too would be great!

**Pull request merged**
