### PR TITLE
[fix][4.1.x] Add HttpOnly flag for JSESSIONID and force cookie only session

### PR DESCRIPTION
**Pull request by cslzchen**
### Version
4.1.x
### Description

Add `HttpOnly` flag to JSESSIONID:
```
<cookie-config>
    <http-only>true</http-only>
</cookie-config>
```
This does not affect the `Secure` flag. For our CAS, it will be `true` for production (https) and `false` for development (http). We guess that the jetty server internally configure the `Secure` flag.

Remove JSESSIONID from url (from https://github.com/apereo/cas/pull/1401)
```
<tracking-mode>COOKIE</tracking-mode>
```

### CODE REVIEW

**Comment by dima767** [comment]
What problem is it trying to "solve"?

**Comment by cslzchen** [comment]
Current JSESSIONID is not protected by HttpOnly.
Before:
cas-jsessionid
After:
cas-jsessionid-httponly

**Comment by mmoayyed** [comment]
@cslzchen Could you submit a pull request for 4.2 as well? Thanks.

**Comment by cslzchen** [comment]
Sure.

**Pull request merged**
