### PR TITLE
DynamoDb naming tables and prevent table creation on startup (5.2.x)

### PR DESCRIPTION
**Pull request by swlyons**
Added the ability to specify the name of the DynamoDb tables and also the ability to skip table creation on startup (This way if CAS doesn't have permissions to create tables your AWS account it won't throw an error on the 'create table if not exist' method).

Already added the info to Configuration-Properties.md the values are:

```
cas.serviceRegistry.dynamoDb.preventTableCreationOnStartup

cas.ticket.registry.dynamoDb.preventTableCreationOnStartup
cas.ticket.registry.dynamoDb.serviceTicketsTableName
cas.ticket.registry.dynamoDb.proxyTicketsTableName
cas.ticket.registry.dynamoDb.ticketGrantingTicketsTableName
cas.ticket.registry.dynamoDb.proxyGrantingTicketsTableName
```

Note: They have default values of what the behavior is expected before this change

This is my first time contributing so any issues for new contributers are probably present. Changes were made in both cas-server-core-configuration, cas-server-support-dynamodb-ticket-registry, and cas-server-support-dynamodb-service-registry. I was building it as 5.2.4-SNAPSHOT and was copying the appropriate maven repos over into my cas-overlay for testing.  So I'm assuming that some mysterious entity out there will update the cas version or that it doesn't matter. If I need to update it let me know.

I don't think it'll be effecting any other pull requests from the brief time I looked at them. I didn't go into incredible detail on each of them though.

### CODE REVIEW

**Comment by swlyons** [comment]
So what did I mess up on? I'd love to fix it.

**Comment by mmoayyed** [comment]
First, thank you very much for the change and welcome to the project as a contributor. Well done :) I'll try to get us started:

> This is my first time contributing so any issues for new contributors are probably present. 

No problem. We are here to help. If you have not already, I recommend you take a peek at this document:
https://apereo.github.io/cas/developer/Contributor-Guidelines.html

> Changes were made in both cas-server-core-configuration, cas-server-support-dynamodb-ticket-registry, and cas-server-support-dynamodb-service-registry. I was building it as 5.2.4-SNAPSHOT and was copying the appropriate maven repos over into my cas-overlay for testing. 

Very nice. The change is perfectly valid. Two things:

1. While you in this patch take care of what I would call *core* entities, you should note that there are other types of tickets present in CAS that go into the registry and by extension dynamodb. You have a few that belong to OAuth, and some in SAML, etc. You may want to consider updating the storage name for all tickets types and externalize those into settings as well. (This is very much an optional thing; just stating it here for transparency)

2. Any new behavior/change/feature introduced into a support branch must be forwarded to the master branch as well, and you're welcome to this in yet another PR. We merge both PRs at the same time since we can't quite afford to present new features in a patch release that would be otherwise absent in the next release. If the change is rather simple, we're more than happy to do that bit ourselves and port it forward. In case it's more complicated, we can the contributor proceed. In this case, it's up to you. The patch is rather simple, but if you prefer to handle that bit as well and port forward, by all means. 

> So I'm assuming that some mysterious entity out there will update the cas version or that it doesn't matter. If I need to update it let me know.

Nothing mysterious about it. For reference, see:

- https://apereo.github.io/cas/developer/Build-Process-5X.html#continuous-integration
- https://apereo.github.io/cas/developer/Contributor-Guidelines.html#how-fast-can-i-consume-the-change

>So what did I mess up on? I'd love to fix it.

Take a look at the state of the Travis CI build. Review the failures and push accordingly until the status turns green. Once the state of the pull is finalized, you can move onto the forwarding business, if you are interested. Sometimes the failures are unrelated because of Travis CI flukes or because someone else (usually me!) has broken the build. In those cases, please ping the PR and we'll try to get it merged and fix issues later on.

Thanks again.

**Comment by swlyons** [comment]
What do you mean by pinging the PR? Like I just don't know what that means.

If I understand you correctly with the OAuth and the SAML on the tickets I don't think we have a reason to customize the names on those at the moment but when I start integrating SAML I may start doing that. We wanted to customize Dynamo Table names since we wanted Stage and Prod to be in the same amazon account but for them not to use the same tables.

I'll go ahead and add it to the master branch and create another pull request I should've thought of doing that when doing this in the first place.

Well the error in Travis CI is "Checkstyle rule violations were found. See the report at: file:///home/travis/build/apereo/cas/core/cas-server-core-configuration/build/reports/checkstyle/main.html" Although I'm unfamiliar with Travis so I don't really know what I'm looking at to fix it. It appears that when I go to more options and click on Requests I see the list of travis builds and it seems like it did this build correctly (#3246 3bf30fc) but when I click details on the link above it says it's errored. So this confuses me and I'm probably just not understanding it. What's going on? I'm fine pinging the PR and figuring this out I just don't who PR is and how to do it.

**Comment by mmoayyed** [comment]
> What do you mean by pinging the PR? Like I just don't know what that means.

Post a comment that says: "Hey, can anyone come do stuff over here please". PR is short of Pull Request. Literally, the patch you're working on.

> Well the error in Travis CI is "Checkstyle rule violations were found. See the report at: file:///home/travis/build/apereo/cas/core/cas-server-core-configuration/build/reports/checkstyle/main.html" Although I'm unfamiliar with Travis so I don't really know what I'm looking at to fix it.

This is not a Travis CI error per se. This is checkstyle examining your changes and the codebase in general to find violations of style guideline that are enforced by the codebase. Run `gradlew tasks` to figure out what tasks are available, and one of them is going to be `checkstyleMain` and `checkStyleTest`. Run those to see the failures. 

Or looks here to configure the IDE with a plugin:
https://apereo.github.io/cas/developer/Build-Process-5X.html


And if you examine the Travis CI more closely, you'll find these:

```
:core:cas-server-core-services-authentication:checkstyleMain
:core:cas-server-core-services-registry:checkstyleMain
:core:cas-server-core-tickets:checkstyleMain[ant:checkstyle] [ERROR] /home/travis/build/apereo/cas/core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/dynamodb/AbstractDynamoDbProperties.java:64:21: Variable 'preventTableCreationOnStartup' explicitly initialized to 'false' (default value for its type). [ExplicitInitialization]
[ant:checkstyle] [ERROR] /home/travis/build/apereo/cas/core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/dynamodb/DynamoDbTicketRegistryProperties.java:33:5: Instance variable definition in wrong order. [DeclarationOrder]
[ant:checkstyle] [ERROR] /home/travis/build/apereo/cas/core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/dynamodb/DynamoDbTicketRegistryProperties.java:46:5: Instance variable definition in wrong order. [DeclarationOrder]
[ant:checkstyle] [ERROR] /home/travis/build/apereo/cas/core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/dynamodb/DynamoDbTicketRegistryProperties.java:59:5: Instance variable definition in wrong order. [DeclarationOrder]
[ant:checkstyle] [ERROR] /home/travis/build/apereo/cas/core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/dynamodb/DynamoDbTicketRegistryProperties.java:72:5: Instance variable definition in wrong order. [DeclarationOrder]
[ant:checkstyle] [ERROR] /home/travis/build/apereo/cas/core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/dynamodb/DynamoDbTicketRegistryProperties.java:75:5: Constructor definition in wrong order. [DeclarationOrder]
```

Fix those.

**Comment by mmoayyed** [comment]
If you examine the build report, you can also see the full command that was executed with that error:

```
./gradlew --stacktrace --parallel -DskipNpmCache=true assemble checkstyleMain checkstyleTest test coveralls
```

**Comment by swlyons** [comment]
K I created another pull request for the master branch, I'll take a look on Monday at what's going on with the Codacy/PR Quality Review and the coverage/coveralls, along with seeing if travis managed to build the master branch. Thanks for helping. It took a while to get my IntelliJ to start using checkstyle but I got it up and running now.

**Comment by swlyons** [comment]
For the Codacy/PR Quality Review when I try to look at the logs I'm seeing a 404 ERROR on the request "URL:https://github.com/login/oauth/authorize?client_id=cdf4908794347d83c413&redirect_uri=https%3A%2F%2Fapp.codacy.com%2Flogin%2FGithubReadOnly%3Fcodacy_skip_ga%3D1&state=NiruKOMjrQ5CdrW7ubJ6Y07OESbCON6sYSPXd5E1&utm_nooverride=".  For the coverage/coveralls.....I'm lost. I don't know what it's saying. For the master branch I'm trying to run the command that failed in travisci (seems to have timed out or something). My computer for some reason thinks that it's running Gradle 5.0 so I'll try to bang my computer around some more until it can run it to make sure it works before sending it out (I think it will, just want to make sure my computer stops freaking out).

**Pull request merged**
