### PR TITLE
Update unit tests for expiration policies

### PR DESCRIPTION
**Pull request by potato04**
In this PR, i moved `clock` field into `AbstractCasExpirationPolicy` so that other subclasses can take advantage of the benefits it brings, mentioned in this PR https://github.com/apereo/cas/pull/4822#discussion_r416585572

Another change that I think should be noted is that I also used the policy clock in AbstractTicket, so that I can mock the `creationTime`/`lastTimeUsed` of the ticket in the test. 

The result is that in `TicketGrantingTicketExpirationPolicyTests` I can not only remove class `MovingTimeTicketExpirationPolicy` but also avoid the cumbersome codes in method `verifyTgtIsExpiredByHardTimeOut`.

### CODE REVIEW

**Comment by potato04** [comment]
There are actually several failed unit tests related to memcached&kryo that require further debugging, and I will make more commits if I can resolve them.

**Comment by mmoayyed** [comment]
Thanks for the follow-up. 

If you do find that test failures are not related to your changes, please leave them be and we'll merge anyway once you're confident.

**Comment by mmoayyed** [comment]
Could you merge with master to resolve conflicts?

**Comment by potato04** [comment]
> Could you merge with master to resolve conflicts?

Yes, conflict has been resolved.

**Comment by mmoayyed** [comment]
LGTM. Thanks very much!

**Pull request merged**
