### PR TITLE
Correct tables and warn on dependencies change

### PR DESCRIPTION
**Pull request by dodok1**
There is significant change in packaging and without modification of overlay it will not work.
I don't see it in release notes.

### CODE REVIEW

**Comment by mmoayyed** [comment]
Thanks. Does this change only add `(Changed in version 5.2!):` to the docs?

**Comment by mmoayyed** [comment]
Also, changelog:
https://apereo.github.io/2017/09/15/520rc3-release/#surrogate-authentication

You don't need to add the warning. master is already 5.2. Please remove the warning. Everything else looks good.

**Comment by dodok1** [comment]
Removed warning, anyway, as I haven't checked all RCx release notes, I lost this information (and several hours).

**Comment by mmoayyed** [comment]
Thanks very much.

**Pull request merged**
