### PR TITLE
Converts Mgmt Webapp to Angular TypeScript

### PR DESCRIPTION
**Pull request by tsschmidt**
This pull request is a conversion of the CAS Management Webapp to a single page web application implemented using Angular/TypeScript.

### CODE REVIEW

**Comment by mindblender** [comment]
Travis,

Seeing errors in the console when I change the service type from "CAS Client" to "SAML2 Service Provider" or "OpenID Connect Client".

Thanks!

**Comment by doodelicious** [comment]
Hi Travis,

I'm doing a code review to prepare this PR for merge into master, and the tooltips are not working in the forms found under services management (tested on macOS Sierra v10.12.5, Chrome 59.0, Safari 10.10.1, Firefox 54.0.1).

**Comment by doodelicious** [comment]
When running the application, Angular notifies in console that it is running in development mode, not production mode.

**Comment by doodelicious** [comment]
When inside a service, 'Username Attribute Provider' tab, and selecting 'Principle Attribute' radio button, getting console errors (file attached):
[UsernameAttributeProvider-PrincipleAttribute_console.log.zip](https://github.com/apereo/cas/files/1160695/UsernameAttributeProvider-PrincipleAttribute_console.log.zip)

**Comment by doodelicious** [comment]
When inside a service, in the 'Service Type' tab, service 'OAauth2 Client' selected in dropdown, please left-align 'OAuth Client ID' form label.

**Comment by doodelicious** [comment]
When selecting 'Manage Services' in the header navigation (upper-right hand side), getting console error: ZoneAware Error (error log attached):
[ManageServicesNavigation_console.log.zip](https://github.com/apereo/cas/files/1160720/ManageServicesNavigation_console.log.zip)

**Comment by tsschmidt** [comment]
> When running the application, Angular notifies in console that it is running in development mode, not production mode.

If using Spring bootRun, I think this is normal since it is not compiled to javascript until run in the browser for debugging.  This should go away if building into a war deploying to a server.

Also is there a way I can respond directly to comments?

**Comment by mmoayyed** [comment]
> If using Spring bootRun, I think this is normal since it is not compiled to javascript until run in the browser for debugging.

It is bootRun. Could we perhaps integrate and wire that step into the build so it works for all cases? Majority of development happens via bootRun and it would be great to make it all consistent with no exceptions.

**Comment by tsschmidt** [comment]
>> If using Spring bootRun, I think this is normal since it is not compiled to javascript until run in the browser for debugging.

>It is bootRun. Could we perhaps integrate and wire that step into the build so it works for all cases? Majority of development happens via bootRun and it would be great to make it all consistent with no exceptions.

I am confused as to what the issue is.  The bootRun step is wired to do a buildDev that will include source maps and metadata so errors found during dev can be linked directly to the TypeScript source.  The console warning is just to let you know it is a dev build.  Building a war will compile with --prod and all code will be compiled fully to javascript and optimized and this warning will not appear in the console.

**Comment by mmoayyed** [comment]
Gotcha; So let me clarify:

When we were testing this yesterday we could see the build running with `--prod` as part of bootRun. Maybe that's where I am wrong? @mindblender could clarify. Even if it's not running with that flag, switching to that particular service type is more of a serious error than just warnings. Tooltips were misplaces on the page and console certainly showed catastrophic errors rather than mere warnings. A screenshot actually might help better; I'll try to see about that unless Jeff beats me to it, or someone else.

In the end this is what should happen from an end-user end-developer perspective:

Running the management in bootRun should work *exactly* as it works with `java -jar` or any other acceptable build command. If there are manual steps in the process, it's best that we automate, and then some.

**Comment by tsschmidt** [comment]
Latest push addresses all the errors mentioned by reviewers except the SAML2 Provider service Type.  I forgot I didn't finish that screen.  

bootRun as far as I can tell is not building with --prod.  Sorry to be thick about this, but are you saying it should compile with --prod so it is the same as building for a war?

A problem I have also noticed with Tooltips, and I am not sure of the cause or the fix, is that they sometimes on the first showing do not correctly show the text.  Moving cursor off and back on again it shows correctly.

Keep the bugs coming and also let me know if there are any over all design/layout/architecture changes that would improve the PR.

**Comment by mmoayyed** [comment]
> bootRun as far as I can tell is not building with --prod. Sorry to be thick about this, but are you saying it should compile with --prod so it is the same as building for a war?

Yes exactly; Are there any drawbacks to this approach? If I understand correctly, running with --prod does minify and obfuscate javascript which might not be ideal for dev. Is that the only issue? I realize I did originally ask for this, thinking it's a required thing for the "SAML2 Provider service Type" changes but if the latter is fixed and the two are now irrelevant, we might safely ignore my objection. 

>Keep the bugs coming and also let me know if there are any over all design/layout/architecture changes that would improve the PR.

Very much appreciate it. One thing I have spoken to Jeff and Jodie about is that perhaps we might take this chance to the JSON payload that is submitted to the backend. It's very cryptic and confusing at this point and I very much dislike the backend implementation of mappings and parsings. I could very much use your help on either front to make sure as this area grows larger, it continues to be maintainable. The RegisteredService model is only going to but grow and we must make change either front is amenable to future changes without resorting to ugly hacks here and there.

**Comment by mmoayyed** [comment]
Also note that master is sort of in flux as @dima767 and I have begun to clean up the CAS configuration model to document things and refactor. Keep merging with master and we shall eventually fix all build failures. We can talk more about the overall plan at the next dev call of course.

**Comment by tsschmidt** [comment]
Latest pushes contain changes for running angular unit tests with Karma.  Admittedly the test are basically just stubs at the moment that ensure a component can be instantiated. It is something we can hopefully build on.  I added an angularTest task to run that executes the test, but is outside of the gradle build for now since I am not sure if/how the Travis CI can run Karma tests.

**Comment by mindblender** [comment]
Travis, if the karma tests are setup as a NPM task, then Travis CI should be able to run them.  Not sure if we run tests normally though since Travis CI has limited build time.

**Comment by doodelicious** [comment]
Hi Travis,

Attached is a screenshot for the tabs. At one point, this was looking fine but the latest code updates have made them uneven again.
screenshot 2017-07-26 14 21 56

**Comment by doodelicious** [comment]
In looking at the changes to this PR that have been made this week, there are still some issues. I had several build issues when pulling down the latest updates. They seemed to be the npm cache and npm install scripts in Gradle. I don't know if it was an issue with downloading packages, as each build error did not reproduce after running again. At this time, this PR is a bit unstable given the amount of updates and fixes required to get it stable. I recommend creating a new branch with these new changes, applying them and doing a thorough developer test to validate all screens are working, all functionality is working, and the styling is consistent with the Apereo master branch before submitting the pull request. If you have any questions regarding my request, feel free to email me jmuramoto|at|unicon|dot|net.

**Comment by tsschmidt** [comment]
Ah yes.  My last commit before needed some changes to test code and a small compile error was introduced that stopped the ng build --prod from succeeding.  Those issues should be fixed with the latest push and hopefully you can build now.

If a feature branch works best or makes it easier for everyone to work on these changes, that is fine by me.

Here are some things to consider for this PR and planned features:

- Things that need to be looked at closely is functionality that required JQuery in the original screens.  We need to either find a way to integrate JQuery back in or retool the components that relied on it.  Right now I think the SAML2 screen is not fully functional.

- I am not completely happy with the up and down arrows that I came up with for ordering services, but I wasn't a big fan of the DnD that was there before either.

- Dates right now are reliant on the HTML5 browsers for Datepicker functionality, so older browsers are not fully supported.  

- A scrollable Tab bar would also be ideal.

For the UI isuues above, ultimately I would like to move on to using these: https://material.angular.io/components

The recently added Datatable and the Datepicker are nice additions and the srolling Tab bar looks great too. 

Since we have made the DomainServicesManager the default in CAS it may make sense to add the Domain screen with this PR, since that is how the services are accessed by CAS now.  Everything still works as expected with just the Services screen though and it could be introduced in a later PR.

The JSON Payload refactor I think could be done as part of this merge or a separate PR later.

**Comment by mmoayyed** [comment]
Per discussions with @tsschmidt, closing the PR for the time being to start anew and continue on a dedicated branch with plans to follow up with a PR prior to the official release.

**Pull request closed without merging**
