### PR TITLE
Update to pac4j v1.9.2 and spring-webmvc v1.1.2

### PR DESCRIPTION
**Pull request by leleuj**
The CAS server widely uses pac4j and some changes in 1.9.2 are breaking ones for CAS. So it's better to upgrade to this version and be more cautious for 1.9.3, 1.9.4...

### CODE REVIEW

**Comment by mmoayyed** [comment]
@leleuj are the changes here better suited for something like 5.1?

**Comment by leleuj** [comment]
In fact, there are some breaking changes brought by pac4j v1.9.2 for CAS 5.0.0. So people won't be able to upgrade to pac4j 1.9.2 if CAS 5.0.0 stays on pac4j 1.9.1.

Though, it could be a CAS 5.0.1.

**Comment by mmoayyed** [comment]
Do breaking changes affect CAS configuration? or these mostly internal components that are now updated?

**Comment by leleuj** [comment]
No configuration change is required, this is indeed mostly internal components.

**Comment by mmoayyed** [comment]
Very good. As long as there are no breaking changes, I am fine with this. Thank you.

**Comment by leleuj** [comment]
Unfortunately, there will be breaking changes. Even if you don't change the Stormpath configuration (`cas.authn.stormpath.*`), using the `pac4j-stormpath` v1.9.2 dependency with the `cas-server-support-stormpath` v5.0.0 dependency would break (unless you merge this PR). And some other cases.

**Comment by leleuj** [comment]
Given the issues with RC2, it's maybe not too late to merge this PR before releasing again RC3.

**Comment by mmoayyed** [comment]
Yes, to clarify: a breaking change to me either has to do with user-focused configuration and properties, or a "public api" that is expected to be used or extended by the user. Given stormpath is a fairly low-key feature, I am not to worries about that bit.

**Comment by lyl2008dsg** [comment]
hi all, I use version cas 5.0.0.RC3-SNAPSHOT. How to configure access to user data from MySQL.
My current configuration "deployerConfigContext.xml"
<alias name="queryDatabaseAuthenticationHandler" alias="primaryAuthenticationHandler"/>
    <alias name="dataSource" alias="queryDatabaseDataSource"/>
    <bean id="dataSource"
          class="com.mchange.v2.c3p0.ComboPooledDataSource"
          p:driverClass="${database.driverClass}"
          p:jdbcUrl="${database.url}"
          p:user="${database.user}"
          p:password="${database.password}"
          p:initialPoolSize="${database.pool.minSize}"
          p:minPoolSize="${database.pool.minSize}"
          p:maxPoolSize="${database.pool.maxSize}"
          p:maxIdleTimeExcessConnections="${database.pool.maxIdleTime}"
          p:checkoutTimeout="${database.pool.maxWait}"
          p:acquireIncrement="${database.pool.acquireIncrement}"
          p:acquireRetryAttempts="${database.pool.acquireRetryAttempts}"
          p:acquireRetryDelay="${database.pool.acquireRetryDelay}"
          p:idleConnectionTestPeriod="${database.pool.idleConnectionTestPeriod}"
          p:preferredTestQuery="${database.pool.connectionHealthQuery}"/>

and "application.properties"

database.driverClass=com.mysql.jdbc.Driver
database.url=jdbc:mysql://127.0.0.1:3306/cas?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false
database.user=root
database.password=123456
database.pool.minSize=6
database.pool.maxSize=18
database.pool.maxWait=10000
database.pool.maxIdleTime=120
database.pool.acquireIncrement=6
database.pool.idleConnectionTestPeriod=30
database.pool.connectionHealthQuery=select 1
database.pool.acquireRetryAttempts=5
database.pool.acquireRetryDelay=2000
cas.jdbc.authn.query.sql=select password from casusers where username=?

**Pull request merged**
