### PR TITLE
Consent webflow initialization fix

### PR DESCRIPTION
**Pull request by arbner**
Working with the consent module, building from master branch, I get the following exception during startup:

```java
2017-08-24 09:21:27,931 ERROR [org.apereo.cas.web.flow.configurer.AbstractCasWebflowConfigurer] - <Cannot find state with id 'generateServiceTicket' in flow 'login' -- Known state ids
are 'array<String>['initialAuthenticationRequestValidationCheck', 'ticketGrantingTicketCheck', 'initializeLoginForm', 'viewLoginForm', 'realSubmit', 'showAuthenticationWarningMessages'
, 'sendTicketGrantingTicket']'>
java.lang.IllegalArgumentException: Cannot find state with id 'generateServiceTicket' in flow 'login' -- Known state ids are 'array<String>['initialAuthenticationRequestValidationCheck
', 'ticketGrantingTicketCheck', 'initializeLoginForm', 'viewLoginForm', 'realSubmit', 'showAuthenticationWarningMessages', 'sendTicketGrantingTicket']'
        at org.springframework.webflow.engine.Flow.getStateInstance(Flow.java:342) ~[spring-webflow-2.4.5.RELEASE.jar:2.4.5.RELEASE]
        at org.springframework.webflow.engine.Flow.getState(Flow.java:214) ~[spring-webflow-2.4.5.RELEASE.jar:2.4.5.RELEASE]
        at org.apereo.cas.web.flow.configurer.AbstractCasWebflowConfigurer.createEvaluateActionForExistingActionState(AbstractCasWebflowConfigurer.java:690) ~[cas-server-core-webflow-5
.2.0-RC3-SNAPSHOT.jar:5.2.0-RC3-SNAPSHOT]
        at org.apereo.cas.web.flow.ConsentWebflowConfigurer.createConsentRequiredCheckAction(ConsentWebflowConfigurer.java:52) ~[cas-server-support-consent-webflow-5.2.0-RC3-SNAPSHOT.j
ar:5.2.0-RC3-SNAPSHOT]
        at org.apereo.cas.web.flow.ConsentWebflowConfigurer.doInitialize(ConsentWebflowConfigurer.java:31) ~[cas-server-support-consent-webflow-5.2.0-RC3-SNAPSHOT.jar:5.2.0-RC3-SNAPSHO
T]
        at org.apereo.cas.web.flow.configurer.AbstractCasWebflowConfigurer.initialize(AbstractCasWebflowConfigurer.java:123) ~[cas-server-core-webflow-5.2.0-RC3-SNAPSHOT.jar:5.2.0-RC3-
SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        ...
```

This fixes it for me, but I'm not sure it's the preferred way of adding dependency.

### CODE REVIEW

**Comment by mmoayyed** [comment]
Thanks for the work. This is not the way this should be handled, because a support module cannot depend on a webapp module. Your approach is correct, just not the implementation.

**Comment by mmoayyed** [comment]
I'll do a quick review to see if I can recommend any better options. I think the approach might be that the configuration class that builds and injects the default webflow actions and states must be given higher priority regardless, so that others follow quite later on. That should take care of other possible issues with other modules that might depend on the presence of default actions and states.

**Comment by mmoayyed** [comment]
Please try with the latest master and see how it holds up. I made sure the webflow context is loaded with the best priority first, and then respositioned the initialization logic to be more explicit.

**Comment by arbner** [comment]
Thanks, works perfectly

**Comment by mmoayyed** [comment]
Excellent. Thank you for the confirmation and I apologize if I stepped over your work. I realized the fix was going to be much larger than anticipated and figured doing it would be quicker and less painful for you. However, A for effort and please continue to test the RC/master as you see fit.

**Pull request closed without merging**
