### PR TITLE
WIP: Return SAML LogoutResponse to RP instead of redirecting to the CAS logout page

### PR DESCRIPTION
**Pull request by krzysztof-zych**
This feature allows to return SAML LogoutResponse to RP after RP sent a SAML LogoutRequest to CAS and if configuration property _cas.authn.samlIdp.logout.returnLogoutResponse_ is set to true.

### CODE REVIEW

**Comment by mmoayyed** [comment]
Thanks very much.

As I understand, when CAS logout is invoked, SAML logout messages are built and passed along to clients, with `SamlProfileSingleLogoutMessageCreator` and family to execute SLO. It also appears that once the setting is on, a logout response is built and returned back to the application without SLO actually taking place, yes? 

What need/problem are you trying to solve here with this patch?

**Comment by krzysztof-zych** [comment]
Hi @mmoayyed 
Yes you are right. Indeed I think there is a bug in this patch. My intention for this PR was that after SAML LogoutRequest sent by Service Provider to the CAS and successful logout, CAS will respond to a SP with SAML LogoutResponse. Some applications depend on this response and will redirect to a specific page after received it.

If you know how to make it possible (without any changes) then let me know. If not, I will prepare fix to execute CAS SLO properly and send LogoutResponse to a SP after that.

**Comment by sdc1992** [comment]
Is there any new progress on this issue? We had a similar issue with Microsoft ADFS, ADFS expected a SAML SLO response instead of redirecting to the CAS logout page.

**Comment by sdc1992** [comment]
For posterity: 
This issue has been resolved in version 6.3.0-RC2.

Related commits:
https://github.com/apereo/cas/commit/c4cedf147fbc6bf9d396bb47f70bed1828d5ad1d
https://github.com/apereo/cas/commit/3f721bb7c5d8dc4e0be38254d7b4f0c49ce6da59

**Pull request closed without merging**
