### PR TITLE
Fix problem with SP metadata that defines multiple ACS endpoints (#4923)

### PR DESCRIPTION
**Pull request by dima767**
(cherry picked from commit 88e8977e11b4cb489bf161bad350cf5a9ed8ba69)

### CODE REVIEW

**Review by mmoayyed — CHANGES_REQUESTED** [review]
Fix all build failures please.

**Comment by dima767** [comment]
Well, it's a straight up cherry pick of a commit that was merged into master, I'm assuming with the same failures. But I'll give it a look.

**Comment by dima767** [comment]
Checkstyle errors fixed. Please note, these do exist now in the master.

**Comment by dima767** [comment]
This failure is unrelated https://github.com/apereo/cas/pull/4977/checks?check_run_id=1419274227

**Comment by dima767** [comment]
Because this URL https://downloads.apache.org/tomcat/tomcat-9/v9.0.39/bin/apache-tomcat-9.0.39.zip is 404

I think it's safe now for this backport to go into `6.2.x`

**Comment by dima767** [comment]
This is the culprit -> https://github.com/apereo/cas/blob/master/ci/tests/webapp/validate-external-webapp.sh#L3

As you could see they dynamically change the version here: https://downloads.apache.org/tomcat/tomcat-9/ which is now 40, so embedding the version in that script is kind of volatile

**Comment by dima767** [comment]
This PR closure by the bot is a mistake. Re-opening

**Comment by mmoayyed** [comment]
Thank you Dima!

**Pull request merged**
