### PR TITLE
Fix SAML POST redirection in authn delegation

### PR DESCRIPTION
**Pull request by leleuj**
Since the `/clientredirect` URL has been turned from a controller into a webflow, there is an issue with the SAML POST redirection binding. It generates the following error:

```java
ERROR [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/cas].[dispatcherServlet]] - <Servlet.service() for servlet [dispatcherServlet] in context with path [/cas] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: Cannot call sendRedirect() after the response has been committed] with root cause>
java.lang.IllegalStateException: Cannot call sendRedirect() after the response has been committed
    at org.apache.catalina.connector.ResponseFacade.sendRedirect(ResponseFacade.java:488) ~[tomcat-embed-core-9.0.68.jar!/:9.0.68]
    at javax.servlet.http.HttpServletResponseWrapper.sendRedirect(HttpServletResponseWrapper.java:141) ~[javax.servlet-api-4.0.1.jar!/:4.0.1]
    at org.springframework.security.web.firewall.FirewalledResponse.sendRedirect(FirewalledResponse.java:48) ~[spring-security-web-5.7.3.jar!/:5.7.3]
    at javax.servlet.http.HttpServletResponseWrapper.sendRedirect(HttpServletResponseWrapper.java:141) ~[javax.servlet-api-4.0.1.jar!/:4.0.1]
    at org.springframework.webflow.mvc.servlet.FlowHandlerAdapter.sendRedirect(FlowHandlerAdapter.java:394) ~[spring-webflow-2.5.1.RELEASE.jar!/:2.5.1.RELEASE]
    at org.springframework.webflow.mvc.servlet.FlowHandlerAdapter.defaultHandleExecutionOutcome(FlowHandlerAdapter.java:341) ~[spring-webflow-2.5.1.RELEASE.jar!/:2.5.1.RELEASE]
    at org.springframework.webflow.mvc.servlet.FlowHandlerAdapter.handleFlowExecutionResult(FlowHandlerAdapter.java:453) ~[spring-webflow-2.5.1.RELEASE.jar!/:2.5.1.RELEASE]
    at org.springframework.webflow.mvc.servlet.FlowHandlerAdapter.handle(FlowHandlerAdapter.java:255) ~[spring-webflow-2.5.1.RELEASE.jar!/:2.5.1.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1070) ~[spring-webmvc-5.3.22.jar!/:5.3.22]
```

when the configuration is the following: `cas.authn.pac4j.saml[X].destination-binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST`.

This PR fixes the issue (test updated).

### CODE REVIEW

**Comment by leleuj** [comment]
Backported to: https://github.com/apereo/cas/pull/5544

**Comment by mmoayyed** [comment]
Do you think you could take one of the existing puppeteer tests in this area and verify this behavior? The test that you added does well, but isn't verifying the ultimate behavior.

**Comment by leleuj** [comment]
Sure. It makes sense as I encountered the problem in a UI manual test. Will do.

**Comment by leleuj** [comment]
@apereocas-bot runci

**Comment by leleuj** [comment]
@apereocas-bot runci

**Comment by leleuj** [comment]
@mmoayyed I have added a Puppeteer test to confirm the fix: it is a simple SAML authn delegation with post binding (I have updated the SimpleSAMLPhp configuration accordingly)

**Pull request merged**
