### PR TITLE
Set missing notBefore property in SAML2 SubjectConfirmation

### LINKED ISSUE #2487: SAML2 SubjectConfirmationData is missing attribute 'NotBefore'
After testing CAS **5.1.0-RC-SNAPSHOT** together with SAP we noticed that the `SubjectConfirmationData` is missing the `NotBefore` attribute.

I spotted that `AbstractSaml20ObjectBuilder` is not setting the attribute in:

```java
    public Subject newSubject(final String nameIdFormat, final String nameIdValue,
                              final String recipient, final ZonedDateTime notOnOrAfter,
                              final String inResponseTo) {

        final SubjectConfirmation confirmation = newSamlObject(SubjectConfirmation.class);
        confirmation.setMethod(SubjectConfirmation.METHOD_BEARER);

        final SubjectConfirmationData data = newSamlObject(SubjectConfirmationData.class);
        data.setRecipient(recipient);
        data.setNotOnOrAfter(DateTimeUtils.dateTimeOf(notOnOrAfter));
        data.setInResponseTo(inResponseTo);

        confirmation.setSubjectConfirmationData(data);

        final Subject subject = newSamlObject(Subject.class);
        subject.setNameID(getNameID(nameIdFormat, nameIdValue));
        subject.getSubjectConfirmations().add(confirmation);
        return subject;
    }
```

I would suggest to deliver the `notBefore` data which is present in `SamlProfileSamlSubjectBuilder` to this method and add it to the subject.

I will provide a PR.

Best
-- Robert

### PR DESCRIPTION
**Pull request by ledermueller**
Closes #2487

### CODE REVIEW

**Comment by mmoayyed** [comment]
Sweet. Fix the build failures please.

**Comment by ledermueller** [comment]
As soon as I get back to my pc.

**Comment by ledermueller** [comment]
Unfortunately I have to ask you to revert this patch. I have encountered multiple issues that I have to investigate first. I will come back as soon as I have found the issue(s).

**Comment by mmoayyed** [comment]
We have a PR that attempts to revert the patch: https://github.com/apereo/cas/pull/2492 do you want this to be merged and then you could continue to work? Or you would rather start with what exists already?

**Comment by mmoayyed** [comment]
Also, what is the collection of SPs you are trying to integrate with? Do you have a list and possibly integration guides you can share with us here?

**Comment by ledermueller** [comment]
Please revert the patch as it seems to be not valid for Web SSO and will cause issues with stricter SPs. I got mislead by the exception of the SAP instance and have to dig deeper what the issue is (next time I will create a PR if I'm 100% sure it solves the issue - sorry).

At the moment I try to integrate the following SAML 2 SPs:
* ADFS 2.0 (done)
* SAP (ongoing)

I don't have any guides and doing this more in a trial and error style.

**Comment by mmoayyed** [comment]
Excellent. Are there any particular "lessons learned" type of notes you can share with us, particularly on the ADFS instance? Was that done to handle Office 365? (Note that CAS claims to provide built-in support for O365 though I believe that behavior needs to be verified)

**Comment by ledermueller** [comment]
After I'm done with integrating I will try to provide some more details (if I'm allowed to) in my free time.
The ADFS integration is unfortunately not about Office 365 its about on site Sharepoint + ADFS.

**Pull request merged**
