### PR TITLE
[fix][4.1.x] Only record failed login attempts for throttling login attempts + Fix misleading warning messages.

### PR DESCRIPTION
**Pull request by cslzchen**
### Version
This PR is for 4.1.x.
I will fix 4.2.x if this looks good to you.

### Issue & Fix
First, only requests that successfully log users in are considered successful. All the rest will trigger `recordSubmissionFailure()` even there is no submission. In our CAS, each login fires two consecutive requests. The first (no form data) will add to the failure throttle, which directly causes the second (with form data) to be blocked (if the threshold is faster than 500 logins/second).
```
Request URL:https://accounts.osf.io/login?service=https://osf.io/&auto=true
Request URL:https://accounts.osf.io/login?service=https://osf.io/
```
To fix this, I simply copy the correct behavior from [master](
https://github.com/apereo/cas/blob/master/cas-server-support-throttle/src/main/java/org/apereo/cas/web/support/AbstractThrottledSubmissionHandlerInterceptorAdapter.java#L85) to [4.1.x](https://github.com/apereo/cas/blob/4.1.x/cas-server-webapp-support/src/main/java/org/jasig/cas/web/support/AbstractThrottledSubmissionHandlerInterceptorAdapter.java#L110).

Second, the warning message and docs are misleading. It took us some time to figure out that this is a "rate" based throttling, which is considered as the expected behavior https://github.com/apereo/cas/issues/486. The fix provided by https://github.com/apereo/cas/issues/719 can be further improved. We explicitly mention "threshold rate" instead of "number of logins in a period of time".

### Further Thoughts (not implemented)
Can we just have `thresholdRate` instead of `failureThreshold` and `failureRangeInSeconds`?

### Much Further Thoughts (not for this PR)
If you are interested, I've implemented an alternative approach which keeps a short queue of recent failed logins for each `ip` or `(ip, user)`. Maybe we can provide both to give users more choices. I will make another PR earlier next week. :)

### CODE REVIEW

**Comment by cslzchen** [comment]
Closed for tests.

**Comment by mmoayyed** [comment]
What happened here? Why close?

**Comment by cslzchen** [comment]
Many tests have failed. I will reopen this as soon as I have fix them. Don't want unfinished PR lingering around. :)

**Comment by mmoayyed** [comment]
Oh quite the contrary. We love lingering PRs :) thanks for keeping up with this .

**Pull request closed without merging**
