### PR TITLE
Remove CLA Assistant badge

### PR DESCRIPTION
**Pull request by KharitonOff**
since there is no CLA to sign, the CLA Assistant badge doesn't make any sense

### CODE REVIEW

**Comment by mmoayyed** [comment]
Thanks for the patch. We are going to have to fix the CLA, rather than removing it. I'll try to look into it later this week.

**Comment by mmoayyed** [comment]
This is now fixed, FYI.

**Comment by turkishcrew** [comment]
All

**Comment by KharitonOff** [comment]
Great, it's surely the better solution than mine 😄

**Pull request closed without merging**
