### PR TITLE
[A11y] aria-hidden on icons

### PR DESCRIPTION
**Pull request by Badatos**
Hello, 
I send you my best wishes for this new year ;)

Here is a new PR improving CAS accessibility

Puppeteer :
* Correct a bug preventing any "attributeValue" call from throwing an exception. (`assert(x, y)` does not compare x & y. replaced by `assert.equal(x, y)`)
* replace some `assert(x===y)` by `assert.equal(x, y)` for better readability (display values instead of variable names when test fail)
* Add tests in pm-change-password-sso & reveal-password scenarii with newly added title attributes

CSS:
* Move "caps warning" icon after password toggle button
* Improve contrasts of danger and warning colors for better accessibility

HTML:
+ Add attribute "aria-hidden='true'" on every "msi" icon to prevent a screen reader from attempting to read it.
+ Remove some wrong `alt` attribute on `a` tags
+ Put the "Toggle Password" string in title attribute of reveal-password button
+ Add missing i18n strings ("Toogle password", "Close" and "Logout request pending" were never translated)

### CODE REVIEW

**Comment by mmoayyed** [comment]
Happy new year to you too! Please resolve the conflicts first.

**Comment by Badatos** [comment]
> Happy new year to you too! Please resolve the conflicts first.

Conflict solved ;)

**Comment by mmoayyed** [comment]
@apereocas-bot runci

**Comment by Badatos** [comment]
The functional tests seems to run correctly :)
The only fail is causing by a "Received fatal alert: certificate_expired", obviously not caused by this PR

**Pull request merged**
