### PR TITLE
Added HiOrg-Server delegated PAC4J authentication support

### PR DESCRIPTION
**Pull request by MartinBoehmer**
Added support for delegating authentication to HiOrg-Server via pac4j.

Relevant configuration properties added:
`cas.authn.pac4j.hiOrgServer.id=`
`cas.authn.pac4j.hiOrgServer.secret=`
`cas.authn.pac4j.hiOrgServer.scope=`

As long as [my pull request to scribejava](https://github.com/scribejava/scribejava/pull/867) has not been merged, you need to build and install my backport for scribejava for this pull request to compile:
https://github.com/MartinBoehmer/scribejava/tree/hiorg-5.3.0

In addition, as long as [my pac4j pull request](https://github.com/pac4j/pac4j/pull/1174) has not been merged, you need to build and install this version of pac4j for this pull request to compile:
https://github.com/MartinBoehmer/pac4j/tree/3.1.x-hiorg

### CODE REVIEW

**Comment by MartinBoehmer** [comment]
Absolutely. Would be great to have this in CAS 6 as well.

**Comment by MartinBoehmer** [comment]
In the login view, all OAuth clients have buttons with their specific logos. I would like to add a signature button for this new client as well. I have a PNG file with the logo of this client.

Where would I place this image file? My guess would be `webapp/resources/static/images`

**Comment by mmoayyed** [comment]
I recommend you keep the changes as generic as possible like all other clients, and adjust css/logo/etc in your overlay. You will have a cas.css file as well as an images directory to use in the overlay. Doesn't make much sense to add these here, as almost ALL CAS deployments simply rip out all UI elements and start customizing them. Given yours is super specific, I recommend you start with the overlay for those changes.

**Comment by MartinBoehmer** [comment]
Okay, thanks. I will keep this the UI adjustments in my overlay. Looking forward to the pac4j 3.2.0 release to finally get this PR ready to be merged.

**Comment by MartinBoehmer** [comment]
@mmoayyed Are you expecting the port forward to be completed prior to closing this PR? As far as I see it, there is nothing more to do in terms of 5.3.x, right?

**Comment by mmoayyed** [comment]
Yes and yes :)

**Comment by mmoayyed** [comment]
Also, please remember to document the new authentication provider in CAS docs.

**Comment by mmoayyed** [comment]
This is now ported forward to master. If you could update the docs, we should be good to merge this one. Thanks again.

**Comment by MartinBoehmer** [comment]
Sorry, I haven't been able to work on the docs until now. I created PRs to update the 5.3.x branch (#3593) and the head (#3594).

**Pull request merged**
