### PR TITLE
Improve style for A11y

### PR DESCRIPTION
**Pull request by Badatos**
This is the first part of Accessibility improvements for CAS. (Initiated by #5875)
This one focus only on styles changes and do not modify any CAS behavior.

Detailed corrections:
* Correct default contrast color (use https://app.contrast-finder.org/ ) (alert panels, buttons, etc...)
* Remove border-radius between password input and reveal-password button
* Increase notification font size (no font can be below 11px for proper a11y )
* Remove every "text-justify" occurences (W3C recommends to never justify text for a11y. See https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Supplemental_Guidance:_Text_Justification)

### CODE REVIEW

**Comment by Badatos** [comment]
Hello,
As requested, I've splitted the #5875 PR in smaller ones.
This is the first one, and as it only focuses on styles changes and do not modify any CAS behavior., can it be reviewed "as is" ?
(I'm working on Pupeteers tests for the next ones)

**Comment by mmoayyed** [comment]
Yes I think this is fine.

Could you please provide before/after screenshots?

**Comment by Badatos** [comment]
Thanks !
I take the screens and send it this afternoon.

**Comment by Badatos** [comment]
Here are the screens:

- Before:
before

- After:
after

Look particularly at:
- The red notification number at top right, slightly larger
- The red error message, more contrasted
- No more round corner between password field and "eye" button

**Comment by Badatos** [comment]
Thank you,
I'll send the second part tomorrow ;)

**Pull request merged**
