### PR TITLE
References to Jasig (instead of Apereo) in Polish and Ukrainian message files--patching master, second try.

### PR DESCRIPTION
**Pull request by WhiteMarlin**
Please refer to issue #2752.

- [] Brief description of changes applied: Occurrences of Jasig changed to Apereo, or removed.
- [] Any documentation on how to configure, test: Select (1) Polish and (2) Ukrainian from the login page and examine the logo title and copyright messages.
- [] Any possible limitations, side effects, etc: It is possible, though unlikely, that application.title is used in a Ukrainian context. Please see the commit comment for justification for its removal.
- [] Reference any other pull requests that might be related: None

### CODE REVIEW

**Comment by mmoayyed** [comment]
Outstanding! Thanks very much and congratulations on submitting your first PRs to the project. Hopefully, plenty more to come.

Are you on Twitter? Wanted to give you a shout out.

**Comment by WhiteMarlin** [comment]
You're welcome, and again, thank YOU for all the handholding! Nope, on FB, but not Twitter.

**Comment by mmoayyed** [comment]
Not a problem. All the same: https://twitter.com/misagh84/status/882705405209477120 Feel free to share :)

**Comment by WhiteMarlin** [comment]
Awwwww... thanks!

**Pull request merged**
