### PR TITLE
Upgrade to ldaptive 1.2

### PR DESCRIPTION
**Pull request by mmoayyed**
Presently in snapshot mode. In this upgrade, a number of new ldaptive namespaces have been added that would make the creation of connection pools and search executors so much easier. I'll let the pull hang for now, until the snapshot becomes available, and will update to the GA when it's released. This will fail for the time being.

### CODE REVIEW

**Comment by mmoayyed** [comment]
In working through namespace config, I removed all refs to Spring Sec schemas.

**Comment by dima767** [comment]
Are there any words when ldaptive `1.2 GA` might become available?

**Comment by mmoayyed** [comment]
See https://groups.google.com/forum/#!topic/ldaptive/JXZioHgvTYk

**Comment by dima767** [comment]
All righty then

**Comment by mmoayyed** [comment]
There exists this: https://github.com/vt-middleware/maven-repo which we can use for the time being to let the build pass, and update to GA when it's available. Going to let the PR hang nonetheless.

**Comment by mmoayyed** [comment]
Relevant issue https://github.com/vt-middleware/ldaptive/issues/82

**Pull request merged**
