### PR TITLE
Remove setters

### PR DESCRIPTION
**Pull request by DavidRG13**
Part of #2184

Remove setters from core modules:

- monitor

### CODE REVIEW

**Comment by DavidRG13** [comment]
Looks like it's failing because of some dependency issue, right? I think I didn't change anything related to this error

**Comment by mmoayyed** [comment]
Merge with master and push once more. Should clean it up. Same with the other pull #2300

**Comment by DavidRG13** [comment]
Still failing... Building fine locally for me, could you please try in local?

**Comment by mmoayyed** [comment]
Sure.

**Comment by mmoayyed** [comment]
This is fine; due to pac4j making breaking changes. Can be cleaned up later.

**Pull request merged**
