### PR TITLE
Fix CAS undeploy LDAP thread failed to stop

### PR DESCRIPTION
**Pull request by leeyc0**
We should properly stop all LDAP connection pools (which is implemented as thread pools) upon CAS undeploy, otherwise these thread will be orphaned at servlet server (if servlet server is not shutdown), causing memory leak.

In tomcat such error will be observed:
`The web application [cas] appears to have started a thread named [XXXXX] but has failed to stop it. This is very likely to create a memory leak.`

FYI, the patch in CasPersonDirectoryConfiguration.java is only a workaround. A more proper fix is modifying LdaptivePersonAttributeDao and add a cleanup method, however it is outside of apereo/cas.

LdapPasswordSynchronizationConfiguration.java is also sort of workaround, but I cannot think of more appropriate way.

Also, I consider vt-middleware/ldaptive#174 to be a bug. There should be a way to check the thread pools is closed or not, instead of blindly sleep for a fixed period and assume the pool is closed.

### CODE REVIEW

**Comment by leeyc0** [comment]
ldaptive maintainer fixed the async shutdown problem, is it possible to update CAS to latest ldaptive snapshot so that I can remove the 5 sec wait?

**Comment by leeyc0** [comment]
The 5 sec wait is removed anyway because the ServletContextListener in #4812 already have 5 sec wait

**Comment by leeyc0** [comment]
still pending for merge

**Comment by leeyc0** [comment]
Found there is more test failure. Need to catch out first (and possibly rewrite some bean tracking using prototype bean scope.

**Comment by leeyc0** [comment]
Now the fix is much more elegant and should pass test cases.

**Comment by leeyc0** [comment]
Prototype bean cannot be disposed automatically, need to study how to dispose manually.

https://stackoverflow.com/questions/50681027/do-spring-prototype-beans-need-to-be-destroyed-manually

**Comment by leeyc0** [comment]
All prototype beans should be properly destroyed now

**Comment by hdeadman** [comment]
> 
> 
> All prototype beans should be properly destroyed now

Are all prototype beans being referenced in a map in DestroyPrototypeBeansPostProcessor for the life of the server being up? That seems like a memory leak if that is the case because they wouldn't be garbage collected even if they aren't used or referenced elsewhere.

**Comment by leeyc0** [comment]
> 
> 
> > All prototype beans should be properly destroyed now
> 
> Are all prototype beans being referenced in a map in DestroyPrototypeBeansPostProcessor for the life of the server being up? That seems like a memory leak if that is the case because they wouldn't be garbage collected even if they aren't used or referenced elsewhere.

Yes, but I cannot think of any other method to properly destroy prototype beans. If you believea it is a concern, then the commit b686537382b1ee36cada8ba75eb49fe6bdb53fda would be a better solution. This explicitly marks all long-lived prototype beans that need to be collected.

**Comment by leeyc0** [comment]
ready for merge

**Comment by leeyc0** [comment]
In this case I would close this PR first, since I will be busy with other things soon. Breaking this PR need some time and multiple PR is required anyway.

**Pull request closed without merging**
