### PR TITLE
set minimium idle count on datasource correctly

### PR DESCRIPTION
**Pull request by hdeadman**
Closes https://github.com/apereo/cas/issues/2459

min idle count was being set to max idle time

This change stops using "jpaProperties.getPool().getMaxIdleTime()).intValue()". I don't know where to use that other than on  bean.setIdleTimeout(jpaProperties.getIdleTimeout()); which already has it's own property. I assume some of properties are broken out into the pool object since they are shared with LDAP pools? Which of the idle timeout properties would you like to use for JPA or should it look at both properties and use the larger (or smaller?) of the two?

I also removed a deprecated method and called the method that the deprecated method currently calls.

### CODE REVIEW

**Comment by mmoayyed** [comment]
This is great. Thanks!

> I assume some of properties are broken out into the pool object since they are shared with LDAP pools? 
Yes. 

> Which of the idle timeout properties would you like to use for JPA or should it look at both properties and use the larger (or smaller?) of the two?

I'd find those to be very confusing.  It appears that `getMaxIdleTime` is ONLY used for for data sources, and nothing else. So how about we simply rename that setting to be `getMinIdleTime` to match the actual setter? Using min-size is not good, because that controls the pool size, and has nothing to do with idle timeouts.

Makes sense?

**Comment by mmoayyed** [comment]
btw Travis is being a bit weird lately, and so don't be alarmed if the PR failed. We'll restart and work together to get it merged of course.

**Comment by hdeadman** [comment]
The thing is that bean.setMinimumIdle() is not about timeouts, it is really
more of the minimum size. How many idle connections should the pool keep
open? I think minimum size is an OK name for the property. The question is
what to do with the maximum idle timeout property which is documented but
not used. It is probably the same as the idletimout property.

**Comment by mmoayyed** [comment]
Cool. Thanks for the explanation. I understand.

My suggestion is, if the max idle setting is documented and yet has no use, it's safe to remove it both form code and docs. It's not used anywhere else right? So lets get rid of it altogether.

**Comment by mmoayyed** [comment]
btw one last thing: It would be greatly helpful if you could start PRs with a "Closes #2459". That helps to auto-close the issue. See https://apereo.github.io/cas/developer/Contributor-Guidelines.html#creating-pull-requests

**Comment by hdeadman** [comment]
I removed maxidletime from all the references in the docs that were jdbc/jpa related, but I also removed it from one ldap related property. I don't see "maxidletime" anywhere in the code now so I don't think it's used but if there is any reflection or copying of bean properties from one bean to another (e.g. beanutils.copyproperties) then I could be missing that.

**Comment by mmoayyed** [comment]
Thank you very much for the contribution. Outstanding work. Keep 'em coming!

**Comment by hdeadman** [comment]
One other thing, I think the hikari datasource ignores any minimum size greater than the max and just sets the min=max. I had maxIdleTime set to 1000 (assuming it was ms) but it was setting the min size of the pool so the connection pool size (min) was equal to the max size for the pool. In my case I had a cas user in postgresql with a connection limit on the database of 30 and I looked into this when I saw an error in the cas logs about it exceeding the connection limit (set in DB). (I had three cas servers running (local and a cluster) and the max pool size was 15).

Might be worth merging to 5.0 branch.

**Comment by mmoayyed** [comment]
Sounds good. Yes, can totally be merged back. Would you rather also that bit, or would you rather I do it?

**Pull request merged**
