### PR TITLE
Fix problem of ssoEnabled setting not working for SAML logins

### PR DESCRIPTION
**Pull request by davidgelhar**
In a SAML authentication, DefaultSingleSignOnParticipationStrategy was incorrectly checking the ssoEnabled setting from the SAML callback service, not the actual registered service.

The InitialFlowSetupAction is doing this to resolve the service:
```java
val service = WebUtils.getService(this.argumentExtractors, context);
val selectedService = authenticationRequestServiceSelectionStrategies.resolveService(service);
val registeredService = this.servicesManager.findServiceBy(selectedService);
```

then storing it in the context:
```java
WebUtils.putRegisteredService(context, registeredService);
```

DefaultSingleSignOnParticipationStrategy.isParticipating() was resolving the service this way:
```java
val service = WebUtils.getService(requestContext);
val registeredService = this.servicesManager.findServiceBy(service);
```
Proposed solution is for isParticipating() to first try WebUtils.getRegisteredService()

### CODE REVIEW

**Comment by mmoayyed** [comment]
Thanks for identifying this. 

What you preferably should do instead is to inject `private final AuthenticationServiceSelectionStrategy serviceSelectionStrategy;` into the SSO strategy `DefaultSingleSignOnParticipationStrategy`, and then follow the same approach where you'd do:

```java
val service = WebUtils.getService(requestContext);
val selectedService = authenticationRequestServiceSelectionStrategies.resolveService(service);
val registeredService = this.servicesManager.findServiceBy(service);
```

Thus removing the need for conditional/specialized logic.

**Comment by mmoayyed** [comment]
@davidgelhar do you think you might have time today to finalize this, or shall we punt for RC6? Do you need more time, and if so, what would be your estimate? Would you prefer if I updated the pull request here with the proposed changes before merging?

**Comment by davidgelhar** [comment]
Hi Misagh,

Yes, I should be able to get to this before the end of the day.

David

**Comment by davidgelhar** [comment]
Actually, looking at your proposed changes a little more carefully, I'm not clear on how to correctly inject an appropriate AuthenticationServiceSelectionStrategy implementation into the DefaultSingleSignOnParticipationStrategy. So, perhaps it would be better if you just update the pull request here if you've already worked that out.

Thanks

**Pull request merged**
