### PR TITLE
References to Jasig (instead of Apereo) in Polish and Ukrainian message files.

### PR DESCRIPTION
**Pull request by WhiteMarlin**
Please refer to issue #2752.

- [] Brief description of changes applied: Occurrences of Jasig changed to Apereo, or removed.
- [] Any documentation on how to configure, test: Select (1) Polish and (2) Ukrainian from the login page and examine the logo title and copyright messages.
- [] Any possible limitations, side effects, etc: It is possible, though unlikely, that application.title is used in a Ukrainian context. Please see the commit comment for justification for its removal.
- [] Reference any other pull requests that might be related: None

### CODE REVIEW

**Comment by mmoayyed** [comment]
Thank you very much for the contribution. Outstanding work. Keep 'em coming!

**Comment by mmoayyed** [comment]
You may be interested in issuing the same patch to the master branch, to ensure the fix continues to exist beyond 5.1.x.

**Comment by mmoayyed** [comment]
Also, since you mentioned you weren't quite sure how to do PRs, here's a better guide: https://apereo.github.io/2017/07/05/cas-contribution-guide/

**Comment by WhiteMarlin** [comment]
You're welcome, and thank YOU.

**Comment by WhiteMarlin** [comment]
I tried doing a PR for master, but it looks like I did it wrong. Can I delete that PR?

**Pull request merged**
