### PR TITLE
ignite config redux

### PR DESCRIPTION
**Pull request by tduehr**
Renames IgniteTicketRegistryConfiguration `@Component` annotation and moves configuration of that class to boot.

### CODE REVIEW

**Comment by tduehr** [comment]
This passes all tests and *should* be correct, but I get strange errors when I try to use it.

~~~
Caused by: org.springframework.beans.ConversionNotSupportedException: Failed to 
convert value of type [java.lang.String] to required type [org.apache.ignite.cac
he.CacheAtomicityMode]; nested exception is java.lang.IllegalStateException: Can
not convert value of type [java.lang.String] to required type [org.apache.ignite
.cache.CacheAtomicityMode]: no matching editors or conversion strategy found
~~~

**Comment by tduehr** [comment]
I just found ignite-spring. It should help clean this up a bunch. I'll give it a shot tomorrow.

**Comment by mmoayyed** [comment]
Sounds good. Let me know if you need any help.

**Comment by mmoayyed** [comment]
This looks like it's ready.

Do we need to update the docs?
Do we need to update the app.properties? 

I know this is targeted towards letsboot. Could I ask you to target it against master? I can live it with it as is, and cherry pick it over to master.

**Comment by tduehr** [comment]
I haven't had a chance to work on this in a while. There are/were some bugs somewhere in 5.0.0-SNAPSHOT that prevent this from working right just yet. This is currently setup for spring boot as well. I'll take a look shortly and provide an update.

**Pull request closed without merging**
