### PR TITLE
Fixing oidc/oauth2 access token to get new expiration time

### PR DESCRIPTION
**Pull request by johnjcool**
Fixing oidc/oauth2 access token to get new expiration time on token refresh, only id token will be refreshed

need port forward

### CODE REVIEW

**Comment by TonCherAmi** [comment]
@johnjcool this does not fix the `iat` date staying the same as that of the initial authentication. I believe this would a better fix:

```diff
diff --git a/support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/OAuth20DefaultTokenGenerator.java b/support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/OAuth20DefaultTokenGenerator.java
index dc2c9467a50..1406a91fb47 100644
--- a/support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/OAuth20DefaultTokenGenerator.java
+++ b/support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/OAuth20DefaultTokenGenerator.java
@@ -201,6 +201,7 @@ public class OAuth20DefaultTokenGenerator implements OAuth20TokenGenerator {
         val clientId = holder.getRegisteredService().getClientId();
         val authn = DefaultAuthenticationBuilder
             .newInstance(holder.getAuthentication())
+            .setAuthenticationDate(ZonedDateTime.now(ZoneOffset.UTC))
             .addAttribute(OAuth20Constants.GRANT_TYPE, holder.getGrantType().toString())
             .addAttribute(OAuth20Constants.SCOPE, holder.getScopes())
             .addAttribute(OAuth20Constants.CLIENT_ID, clientId)

```

**Comment by johnjcool** [comment]
@TonCherAmi: you're right. i will try with our setup and fix the pull request.

**Comment by TonCherAmi** [comment]
@mmoayyed without this fix the refresh token grant literally does not function, can it be reviewed as soon as possible, please?

**Comment by johnjcool** [comment]
where can i see the test report of the build -> file:///home/travis/build/apereo/cas/support/cas-server-support-oauth/build/reports/tests/testOAuth/index.html

**Comment by mmoayyed** [comment]
Log is available here: https://travis-ci.org/github/apereo/cas/jobs/686744151

```
> Task :support:cas-server-support-oauth:testOAuth
org.apereo.cas.support.oauth.web.response.accesstoken.OAuth20DefaultTokenGeneratorTests > verifyAccessTokenIsRefreshed() FAILED
    org.opentest4j.AssertionFailedError: expected: not equal but was: <1589423887>
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
        at org.junit.jupiter.api.AssertNotEquals.failEqual(AssertNotEquals.java:276)
        at org.junit.jupiter.api.AssertNotEquals.assertNotEquals(AssertNotEquals.java:121)
        at org.junit.jupiter.api.AssertNotEquals.assertNotEquals(AssertNotEquals.java:113)
        at org.junit.jupiter.api.Assertions.assertNotEquals(Assertions.java:2045)
        at org.apereo.cas.support.oauth.web.response.accesstoken.OAuth20DefaultTokenGeneratorTests.verifyAccessTokenIsRefreshed(OAuth20DefaultTokenGeneratorTests.java:80)
```

**Pull request merged**
