### PR TITLE
Adding Apache Syncope attribute resolution

### PR DESCRIPTION
**Pull request by ilgrosso**
This PR adds support for Attribute Resolution by searching into an Apache Syncope instance via REST.

### CODE REVIEW

**Comment by ilgrosso** [comment]
@mmoayyed just wanted you to have a look before I go too much far with testing: WDYT?

**Comment by mmoayyed** [comment]
Looks good to me, thank you! Please continue. One question: are you sure you don't need to implement getPeople() instead? I don't think getPerson is called by CAS.

See: https://github.com/apereo/cas/blob/master/core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/attribute/PrincipalAttributeRepositoryFetcher.java#L70

PS I am doing some minor amount of cosmetic work on person directory to make it easier to build DAOs and remove noise with templated methods. This would not affect you and this PR just yet, but if I get done, I might have to ask you to remove the "empty" methods from the DAO

**Comment by mmoayyed** [comment]
Also so I understand: the use case might be that you would verify user credentials using some other/alternative method and yet you'd want to fetch attributes from Syncope separately. Is that the case?

**Comment by ilgrosso** [comment]
> One question: are you sure you don't need to implement getPeople() instead? I don't think getPerson is called by CAS.

Thanks, I'll go ahead and ensure that both methods are implemented.

> I might have to ask you to remove the "empty" methods from the DAO

Sure!

> the use case might be that you would verify user credentials using some other/alternative method and yet you'd want to fetch attributes from Syncope separately. Is that the case?

That's correct: Given such use case, I wanted to re-use the parsing logic.

**Comment by ilgrosso** [comment]
@mmoayyed one question: how can I fix Mergify failure? Sorry, first time I am encountering this...

**Comment by mmoayyed** [comment]
You can ignore that for now. I'll look into it. This used to be valid with Travis CI; should be inactive now and likely removed.

**Comment by mmoayyed** [comment]
@apereocas-bot runci

**Comment by mmoayyed** [comment]
@apereocas-bot runci

**Comment by mmoayyed** [comment]
Thanks very much. This looks excellent, and I went ahead and merged it out of band. Should get published in an hour or so, and I also integrated other changes for automated integration tests for syncope. 

You can use `./testcas.sh --category syncope` to run syncope-tagged tests.

**Comment by mmoayyed** [comment]
For archives, the commit entry is: https://github.com/apereo/cas/commit/a34ce89abb4ec00c8de32ec9d9452578e2569696

**Comment by ilgrosso** [comment]
Thank you very much @mmoayyed !

**Pull request closed without merging**
