### PR TITLE
Cleaning unchecked warnings

### LINKED ISSUE #2168: Clean "uses unchecked or unsafe operations." warnings
There are lot of messages like ```Note: /home/travis/build/apereo/cas/support/cas-server-support-gauth/src/main/java/org/apereo/cas/config/GoogleAuthenticatorConfiguration.java uses unchecked or unsafe operations.``` in the build logs.

Would you mind if I try to clean the most I can?

### PR DESCRIPTION
**Pull request by DavidRG13**
Closes #2168 

Just explicitly specified the type

There are more warnings, I just remove about half of them, the rest need a deeply look at they have type conflics

### CODE REVIEW

**Comment by DavidRG13** [comment]
@mmoayyed could you please confirm that the error has something to do with my changes?

Thanks a lot!

**Comment by mmoayyed** [comment]
Yup. It certainly does look like it. Given that master is building fine, this is all you :)

**Comment by DavidRG13** [comment]
Not sure mate, still getting ```net.sf.ehcache.CacheException: Problem starting listener for RMICachePeer //95.131.186.35:41001/org.apereo.cas.ticket.TicketCache. Initial cause was Connection refused to host: 95.131.186.35``` and ```rror creating bean with name 'mongoDbEventsRepository': Invocation of init method failed; nested exception is org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting for a server that matches WritableServerSelector.```

Am I missing any configuration? Also happening in master

**Comment by mmoayyed** [comment]
Well it may be something in your environment perhaps because Travis is building master find and I also can run all tests correctly on master. Any particular changes recently made to your dev environment?

**Comment by DavidRG13** [comment]
Nothing changed mate... Now master is failing because of missing dependencies...
```
location: class DefaultOAuthCasClientRedirectActionBuilder
/home/davidrodriguez/dev/casApereo/support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/OAuthCasClientRedirectActionBuilder.java:24: error: cannot find symbol
    RedirectAction build(CasClient casClient, WebContext context);

```

Will wait until I can build master fine to merge with this and fix it. 

Maybe this failure is related to any spring config, that can't inject typed lists... (I was considering to revert this and do smallest steps)

**Comment by mmoayyed** [comment]
That I believe I have fixed. This is due to pac4j running on snapshots. Merge with master once and let Travis build. If that still fails then let's close this maybe and start with more incremental changes.

**Comment by DavidRG13** [comment]
Given that I can't find the reason for this to fail and that doing #2184 I'll touch lot of classes I'm doing this unchecked warning cleaning there, so we can close this.

When #2184 is finished we should review unchecked again, and clean the remainings

**Pull request closed without merging**
