### PR TITLE
JPA fixing hanging connections on saml auth 

### PR DESCRIPTION
**Pull request by johnjcool**
Brief description of changes applied:
fixing hanging connections on saml auth because of default fetch typ lazy. switching to fetch type eager like in AbstractRegisteredService fixes the problem of hanging connections.

```
o.s.c.s.i.w.ExceptionLoggingFilter : Uncaught exception thrown
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: org.apereo.cas.support.saml.services.SamlRegisteredService.attributeFriendlyNames, no session or session was closed
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:645) ~[javax.servlet-api-4.0.1.jar!/:4.0.1]
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar!/:4.0.1]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-catalina-9.0.31.jar!/:9.0.31]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-catalina-9.0.31.jar!/:9.0.31]
at brave.servlet.TracingFilter.doFilter(TracingFilter.java:65) ~[brave-instrumentation-servlet-5.8.0.jar!/:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-catalina-9.0.31.jar!/:9.0.31]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-catalina-9.0.31.jar!/:9.0.31]
at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:64) ~[spring-webmvc-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-catalina-9.0.31.jar!/:9.0.31]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-catalina-9.0.31.jar!/:9.0.31]
at org.apereo.cas.web.support.AuthenticationCredentialsThreadLocalBinderClearingFilter.doFilter(AuthenticationCredentialsThreadLocalBinderClearingFilter.java:28) ~[cas-server-core-web-api-6.1.5.jar!/:6.1.5]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-catalina-9.0.31.jar!/:9.0.31]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-catalina-9.0.31.jar!/:9.0.31]
at org.apereo.cas.web.support.filters.RequestParameterPolicyEnforcementFilter.doFilter(RequestParameterPolicyEnforcementFilter.java:411) ~[cas-server-core-web-api-6.1.5.jar!/:6.1.5]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-catalina-9.0.31.jar!/:9.0.31]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-catalina-9.0.31.jar!/:9.0.31]
at org.apereo.cas.web.support.filters.ResponseHeadersEnforcementFilter.doFilter(ResponseHeadersEnforcementFilter.java:215) ~[cas-server-core-web-api-6.1.5.jar!/:6.1.5]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-catalina-9.0.31.jar!/:9.0.31]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-catalina-9.0.31.jar!/:9.0.31]
at org.apereo.cas.web.support.filters.AddResponseHeadersFilter.doFilter(AddResponseHeadersFilter.java:67) ~[cas-server-core-web-api-6.1.5.jar!/:6.1.5]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-catalina-9.0.31.jar!/:9.0.31]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-catalina-9.0.31.jar!/:9.0.31]
```
```
org.hibernate.AssertionFailure: bug adding collection twice
  at org.hibernate.engine.internal.StatefulPersistenceContext.addCollection(StatefulPersistenceContext.java:920) ~[hibernate-core-5.4.9.Final.jar!/:5.4.9.Final]
  at org.hibernate.engine.internal.StatefulPersistenceContext.addUninitializedDetachedCollection(StatefulPersistenceContext.java:895) ~[hibernate-core-5.4.9.Final.jar!/:5.4.9.Final]
  at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:257) ~[hibernate-core-5.4.9.Final.jar!/:5.4.9.Final]
  at org.hibernate.collection.internal.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:162) ~[hibernate-core-5.4.9.Final.jar!/:5.4.9.Final]
  at org.hibernate.collection.internal.PersistentMap.size(PersistentMap.java:148) ~[hibernate-core-5.4.9.Final.jar!/:5.4.9.Final]
  at java.util.HashMap.putMapEntries(Unknown Source) ~[?:?]
  at java.util.HashMap.putAll(Unknown Source) ~[?:?]
  at org.apereo.cas.support.saml.web.idp.profile.builders.attr.SamlProfileSamlAttributeStatementBuilder.buildAttributeStatement(SamlProfileSamlAttributeStatementBuilder.java:71) ~[cas-server-support-saml-idp-web-6.1.5.jar!/:6.1.5]
  at org.apereo.cas.support.saml.web.idp.profile.builders.attr.SamlProfileSamlAttributeStatementBuilder.build(SamlProfileSamlAttributeStatementBuilder.java:55) ~[cas-server-support-saml-idp-web-6.1.5.jar!/:6.1.5]
  at org.apereo.cas.support.saml.web.idp.profile.builders.attr.SamlProfileSamlAttributeStatementBuilder.build(SamlProfileSamlAttributeStatementBuilder.java:30) ~[cas-server-support-saml-idp-web-6.1.5.jar!/:6.1.5]
  at jdk.internal.reflect.GeneratedMethodAccessor577.invoke(Unknown Source) ~[?:?]
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
  at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
  at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:279) ~[spring-core-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
  at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(GenericScope.java:499) ~[spring-cloud-context-2.2.0.RC1.jar!/:2.2.0.RC1]
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
  at com.sun.proxy.$Proxy372.build(Unknown Source) ~[?:?]
  at org.apereo.cas.support.saml.web.idp.profile.builders.assertion.SamlProfileSamlAssertionBuilder.build(SamlProfileSamlAssertionBuilder.java:83) ~[cas-server-support-saml-idp-web-6.1.5.jar!/:6.1.5]
  at org.apereo.cas.support.saml.web.idp.profile.builders.assertion.SamlProfileSamlAssertionBuilder.build(SamlProfileSamlAssertionBuilder.java:37) ~[cas-server-support-saml-idp-web-6.1.5.jar!/:6.1.5]
  at jdk.internal.reflect.GeneratedMethodAccessor577.invoke(Unknown Source) ~[?:?]
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
  at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
```
Test cases for all modified changes, where applicable:
Testcases which covers this change
- SamlRegisteredServiceJpaTests
- SamlRegisteredServiceJpaPostgresTests
- SamlRegisteredServiceJpaMicrosoftSqlServerTests

The same pull request targeted at the master branch, if applicable:
after merge cherry pick to master? the pull request is not compatible to master branch. port forward to master needed.

### CODE REVIEW

**Comment by johnjcool** [comment]
I am disappointed to get no feedback from any cas core developer... whether on github nor on Gitter. The build problem are LDAP tests. Not my fault. The branch is broken. Did you really want help to fix bugs? Think about your communication strategy.

**Comment by mmoayyed** [comment]
Can you please review:

1. What do you mean by hanging connections? can you update the PR to explain the problem more clearly, and discuss what and when and why? 
2. Can you attach logs showing errors, if there is any? 
3. Are there test cases accounting for the changes you have made?
4. Does this patch need to be ported forward to master?

**Comment by johnjcool** [comment]
answered questions

**Comment by mmoayyed** [comment]
Thanks for the answers. Could you design a test case to actually demonstrate the problem?

**Comment by johnjcool** [comment]
this is not trivial because it is kind of integration test instead of unit test. you need serviceregistry, database and saml process (first call and callback) in the testcase. 

process:
first saml request -> serviceregistry reload -> callback saml request

if there is a template test class with these function all together i can try. but without im lost.

**Comment by johnjcool** [comment]
i also looked at AbstractRegisteredServiceTests how the eager fetch type is tested and there is no template for this kind of test.

**Comment by mmoayyed** [comment]
Without a test case, it's unclear whether the change actually does anything and it's also unclear how we might protect against this in the future if CAS or hibernate behavior changes on the next patch. You don't need to test hibernate. Hibernate tests hibernate. You should try with any of the JPA test cases to duplicate the flow, that also load SAML services and those should be a good-enough start point. I am also not sure whether you need a full SAML flow; it seems like it might be doable with a JPA service registry that loads SAML definitions.

Alternatively, you can:

1. provide a CAS overlay template with the bare minimum changes that one can run to demonstrate the problem. That way, we can see this reproduced in action and help you better with a possibility of a test case.
2. turn the pull request into draft/WIP and we can try to look into a better test case with allocated time as schedules become available.

**Comment by mmoayyed** [comment]
Also, your stacktrace shows that you are running 6.1.5. A good test would be to try 6.1.6 and see if that changes anything for the better?

**Comment by johnjcool** [comment]
hello,

we have tested with 6.1.6 and get the same issue. another workaround is to set `<spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true>`. but this bad practice. 

it works in general. we see this error in special situations of refreshing the services in the serviceregistry and an SAML Callback request. we decided to write no testcase for this special situation because it consumes to much time. adding fetch type eager at ElementCollection fixes our problem. 

it is also done at https://github.com/apereo/cas/blob/e87ee01af408575163984da5353b449393a05046/core/cas-server-core-services-api/src/main/java/org/apereo/cas/services/AbstractRegisteredService.java#L163  and so it is consistent. btw there is also no test which covers fetch type eager. 

we also found this ticket in jasig cas https://apereo.atlassian.net/browse/CAS-863. the decompiled code of 3.4.1 and 3.4.2 shows that there is a switch from lazy to eager. 

merge it or close the pull request.

**Comment by mmoayyed** [comment]
Thanks very much for the update. Without tests we are unable to verify that the fix does in fact fix anything and it's unclear how to protect against the failure. In the absence of reproducible proof, the best course of action is to do anything until a more verifiable proof shows up.

**Pull request closed without merging**
