### PR TITLE
Add the logout audit

### PR DESCRIPTION
**Pull request by leleuj**
To track the logout event.

### CODE REVIEW

**Comment by mmoayyed** [comment]
The changeset here appears to break CAS:

```
Caused by:
                    java.lang.IllegalArgumentException: Cannot subclass final class org.apereo.cas.logout.DefaultLogoutManager
                        at org.springframework.cglib.proxy.Enhancer.generateClass(Enhancer.java:653)
                        at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:26)
                        at org.springframework.cglib.core.ClassLoaderAwareGeneratorStrategy.generate(ClassLoaderAwareGeneratorStrategy.java:57)
                        at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:362)
                        at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:575)
                        at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.lambda$new$1(AbstractClassGenerator.java:103)
                        at org.springframework.cglib.core.internal.LoadingCache.lambda$createEntry$1(LoadingCache.java:52)
                        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                        at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:57)
                        at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
                        at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:126)
                        at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:313)
                        at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:562)
                        at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:407)
                        at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:62)
                        at org.springframework.aop.framework.CglibAopProxy.buildProxy(CglibAopProxy.java:213)
                        ... 141 more
```

Is this something you did see as well?

**Comment by leleuj** [comment]
Sorry. I missed your message. I haven't seen that error. From which test did it come from? I can investigate...

**Comment by mmoayyed** [comment]
No worries. I think any test in master that tried to create the `DefaultLogoutManager` bean started to fail; likely because the component was mistakenly changed to be a Java record, which are always final, and cannot be proxied. This should be fixed now.

**Comment by mmoayyed** [comment]
PS To clarify, the mistake to use records here was mine...or rather me trusting IDEA way too much :) It wasn't part of the changeset you proposed.

**Pull request merged**
