### PR TITLE
CAS Management Webapp 5.2 : issue with attributes to release

### PR DESCRIPTION
**Pull request by lsenecaux**
Hello,
I'm having a problem with the service management app.
Indeed, I select the attributes to return for a given service then I save it.
When I edit this service, the attribute list is gone and the "return all" option is selected.
This problem does not exist on version 5.1.
Thank you

### CODE REVIEW

**Comment by mmoayyed** [comment]
It is unclear what this pull request exactly does. Please rebase/merge with master and try again please with a new pull request. Thank you.

**Comment by lsenecaux** [comment]
excuse me, I am lost since we can no longer post a issue.

**Comment by lsenecaux** [comment]
I would just post an issue, not a PR.
How can I do ?

**Comment by mmoayyed** [comment]
Please see:

- [Maintenance Policy](https://apereo.github.io/cas/developer/Maintenance-Policy.html)
- [Release Policy](https://apereo.github.io/cas/developer/Release-Policy.html)
- [Contributor Guidelines](https://apereo.github.io/cas/developer/Contributor-Guidelines.html)

**Pull request closed without merging**
