### PR TITLE
X509 Rest Authentication fixes.

### PR DESCRIPTION
**Pull request by ruckc**
additional changes to improve X509 REST Authentication.  Moved X509CertificateExtractor to a separate @Configuration so both webflow and rest have access to it.  Plus relaxed @RequestBody requirement to optional, and added != null checks to the CredentialFactories

### CODE REVIEW

**Comment by ruckc** [comment]
all of the travis test failures are from the merge with master, just updated again to see if they are fixed.

**Comment by ruckc** [comment]
I have no clue how to troubleshoot this x509 webflow failure: 
`org.apereo.cas.adaptors.x509.web.flow.X509CertificateCredentialsRequestHeaderActionTests > verifyCredentialsResultsInAuthnFailure FAILED
    org.junit.ComparisonFailure: expected:<[authenticationFailure]> but was:<[error]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.apereo.cas.adaptors.x509.web.flow.X509CertificateCredentialsRequestHeaderActionTests.verifyCredentialsResultsInAuthnFailure(X509CertificateCredentialsRequestHeaderActionTests.java:45)`

It also seems something in the changes this past week has now broken local builds for me, even if I completely clean slate the build environment.
`
> Task :webapp:cas-server-webapp-jetty:nodeSetup FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of output files for task ':webapp:cas-server-webapp-jetty:nodeSetup' property 'nodeDir' during up-to-date check.
> Could not list contents of '/home/ruckc/Repositories/apereo-cas-6/webapp/cas-server-webapp-jetty/.gradle/nodejs/node-v8.11.2-linux-x64/bin/npm'. Couldn't follow symbolic link.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.`

Any suggestions would be appreciated.

**Comment by mmoayyed** [comment]
Are you seeing that error when you run the test locally or on travis ci?

**Comment by mmoayyed** [comment]
Issue here is that your extractor bean id is not in fact what is referenced by the call sites. You had the bean defined as X and then you had Qualifier references refer to it as Y. Since the references used ObjectProvider, you'd always get a null object for the extractor due to the bean naming mismatch, and thus the failure. This has been fixed.

**Pull request merged**
