### PR TITLE
Add missing geolocation hidden input

### PR DESCRIPTION
**Pull request by pdrados**
Without this input, geolocation info is not recorded for the TGT creation event.

### CODE REVIEW

**Comment by mmoayyed** [comment]
You probably need to ensure the same field is added to all other views, right?

**Comment by mmoayyed** [comment]
What about duo, authy and other MFA login views?

**Comment by pdrados** [comment]
I can only assume that it is also needed in other MFA login views, but I can not really see/test it. Since I don't see any harm on adding this input (even if it is not needed), do you want me to add it?

**Comment by mmoayyed** [comment]
Yes please add it. Chances are it actually is needed. 

Also, what do you have tuned on in CAS that takes advantage of this geolocation field? Does GAuth on its own work fine, or are you doing additional things in the overlay that process that? I understand you're recording authN events. What else are you doing next with them? anything?

**Comment by pdrados** [comment]
Risk based authentication is affected by this issue, as geolocation info on TGTs is used when calculating authentication risk.

**Comment by mmoayyed** [comment]
Excellent, thank you.

**Pull request merged**
