### PR TITLE
Update casServiceValidationSuccess.html

### PR DESCRIPTION
**Pull request by zawn**

### CODE REVIEW

**Comment by mmoayyed** [comment]
Thanks

**Comment by mmoayyed** [comment]
@zawn when you get a chance please sign this:
https://www.apereo.org/licensing/agreements/icla

**Comment by zawn** [comment]
@mmoayyed https://www.apereo.org/licensing/agreements/icla submitted

**Comment by mmoayyed** [comment]
Thanks! Keep the pulls coming.

**Pull request merged**
