### PR TITLE
Fix Forgot Username Reference

### PR DESCRIPTION
**Pull request by pspaude**
Note that in casForgotUesrnameSendInfoView.html the id has been changed to "username" and the email reference in this action no longer works. Updating the action to match the view.

### CODE REVIEW

**Review by dima767 — APPROVED** [review]

**Comment by mmoayyed** [comment]
Closing due to inactivity. Feel free to resume as time allows.

**Comment by pspaude** [comment]
With all due respect this is a "bug" and causes forgot username to *not* work in current CAS, I strongly suggest merging the fix or otherwise adjust the references to be in sync.

**Comment by mmoayyed** [comment]
From the contribution guidelines:

> Patches submitted to the codebase in form of pull requests are generally reviewed as quickly as possible and most are often accepted. If you find your contribution to take longer than usual to be merged, it’s possible that the proposed changeset violates one or more of the following principals:

> The patch fails to pass automated unit or integration tests.
> The patch fails to provide adequate unit or integration tests for the proposed changes.
> The patch has remained stale for quite a while without any sign of contributor activity.

And:
image


HTH.

**Comment by mmoayyed** [comment]
Test process is documented here:
https://apereo.github.io/cas/development/developer/Test-Process.html

**Comment by pspaude** [comment]
Great thanks for the pointers. It also looks like it was fixed upstream after this PR was created, thanks! https://github.com/apereo/cas/commit/07e66a2ca0410e0b76ff26273627b77b3157bf10

**Pull request closed without merging**
