### PR TITLE
Make creationTime CasEvent's property

### PR DESCRIPTION
**Pull request by pdrados**
creationTime should be CasEvent's property (as in AbstractCasEventRepository)
or else an IllegalArgumentException is thrown
(InitialAuthenticationAttemptWebflowEventResolver).

```
2017-06-26 15:23:13,982 TRACE [org.apereo.cas.audit.spi.ThreadLocalPrincipalResolver] - <Resolving principal at audit point [execution(AuthenticationRiskScore org.apereo.cas.impl.engine.DefaultAuthe
nticationRiskEvaluator.eval(Authentication,RegisteredService,HttpServletRequest))] with thrown exception [java.lang.IllegalArgumentException: org.hibernate.QueryException: could not resolve property
: creationTime of: org.apereo.cas.support.events.dao.CasEvent [SELECT r from org.apereo.cas.support.events.dao.CasEvent r where r.type = :type and r.creationTime >= :creationTime and r.principalId =
 :principalId]]>
2017-06-26 15:23:13,986 WARN [org.apereo.cas.web.flow.resolver.impl.InitialAuthenticationAttemptWebflowEventResolver] - <org.hibernate.QueryException: could not resolve property: creationTime of: or
g.apereo.cas.support.events.dao.CasEvent [SELECT r from org.apereo.cas.support.events.dao.CasEvent r where r.type = :type and r.creationTime >= :creationTime and r.principalId = :principalId]>
java.lang.IllegalArgumentException: org.hibernate.QueryException: could not resolve property: creationTime of: org.apereo.cas.support.events.dao.CasEvent [SELECT r from org.apereo.cas.support.events
.dao.CasEvent r where r.type = :type and r.creationTime >= :creationTime and r.principalId = :principalId]
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:131) ~[hibernate-core-5.2.10.Final.jar:5.2.10.Final]
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:155) ~[hibernate-core-5.2.10.Final.jar:5.2.10.Final]
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:162) ~[hibernate-core-5.2.10.Final.jar:5.2.10.Final]
        at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:663) ~[hibernate-core-5.2.10.Final.jar:5.2.10.Final]
        at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:679) ~[hibernate-core-5.2.10.Final.jar:5.2.
...
...
...
        at org.apereo.cas.impl.calcs.BaseAuthenticationRequestRiskCalculator.getCasTicketGrantingTicketCreatedEventsFor(BaseAuthenticationRequestRiskCalculator.java:84) ~[cas-server-support-electrofence-5.1.1.jar:5.1.1]
        at org.apereo.cas.impl.calcs.BaseAuthenticationRequestRiskCalculator.calculate(BaseAuthenticationRequestRiskCalculator.java:47) ~[cas-server-support-electrofence-5.1.1.jar:5.1.1]
...
...
...
Caused by: org.hibernate.QueryException: could not resolve property: creationTime of: org.apereo.cas.support.events.dao.CasEvent [SELECT r from org.apereo.cas.support.events.dao.CasEvent r where r.type = :type and r.creationTime >= :creationTime and r.principalId = :principalId]
        at org.hibernate.QueryException.generateQueryException(QueryException.java:120) ~[hibernate-core-5.2.10.Final.jar:5.2.10.Final]
        at org.hibernate.QueryException.wrapWithQueryString(QueryException.java:103) ~[hibernate-core-5.2.10.Final.jar:5.2.10.Final]
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:217) ~[hibernate-core-5.2.10.Final.jar:5.2.10.Final]
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:141) ~[hibernate-core-5.2.10.Final.jar:5.2.10.Final]
        at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:115) ~[hibernate-core-5.2.10.Final.jar:5.2.10.Final]
        at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:77) ~[hibernate-core-5.2.10.Final.jar:5.2.10.Final]
        at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:153) ~[hibernate-core-5.2.10.Final.jar:5.2.10.Final]
        at org.hibernate.internal.AbstractSharedSessionContract.getQueryPlan(AbstractSharedSessionContract.java:546) ~[hibernate-core-5.2.10.Final.jar:5.2.10.Final]
        at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:655) ~[hibernate-core-5.2.10.Final.jar:5.2.10.Final]
        ... 459 more
```

### CODE REVIEW

**Comment by mmoayyed** [comment]
Thank you very much. Please remember to format messages using back ticks. Makes it easier for everyone to review and understand the case.

**Comment by pdrados** [comment]
Could you please explain what do you mean about using back ticks? Where/how should I use them?
Thanks, in advance.

**Comment by mmoayyed** [comment]
Sure. If you notice above in the original issue report, I reformatted the exception stacks to use formatted blocks.  Backticks or triple backticks for code blocks can be very helplful for others to read the code/problem and understand what's going on.

So rather than pasting:

2017-06-26 15:23:13,982 TRACE [org.apereo.cas.audit.spi.ThreadLocalPrincipalResolver] - <Resolving principal at audit point [execution(AuthenticationRiskScore org.apereo.cas.impl.engine.DefaultAuthe
nticationRiskEvaluator.eval(Authentication,RegisteredService,HttpServletRequest))] with thrown exception [java.lang.IllegalArgumentException: org.hibernate.QueryException: could not resolve property
: creationTime of: org.apereo.cas.support.events.dao.CasEvent [SELECT r from org.apereo.cas.support.events.dao.CasEvent r where r.type = :type and r.creationTime >= :creationTime and r.principalId =
 :principalId]]>

Use:

```
2017-06-26 15:23:13,982 TRACE [org.apereo.cas.audit.spi.ThreadLocalPrincipalResolver] - <Resolving principal at audit point [execution(AuthenticationRiskScore org.apereo.cas.impl.engine.DefaultAuthe
nticationRiskEvaluator.eval(Authentication,RegisteredService,HttpServletRequest))] with thrown exception [java.lang.IllegalArgumentException: org.hibernate.QueryException: could not resolve property
: creationTime of: org.apereo.cas.support.events.dao.CasEvent [SELECT r from org.apereo.cas.support.events.dao.CasEvent r where r.type = :type and r.creationTime >= :creationTime and r.principalId =
 :principalId]]>
```

Or here is one color coded for bash:

```bash
ls -al *.txt > grep -v "something"
```

More  here:
https://unix.stackexchange.com/questions/27428/what-does-backquote-backtick-mean-in-commands

**Comment by mmoayyed** [comment]
You can also use the github editor to make your life slightly easier:
image

**Pull request merged**
