### PR TITLE
Forward for Accept header #2815

### PR DESCRIPTION
**Pull request by fedon**
-   [] Provides fair header processing
-   [] Provide Accept: header of your choice
-   [] Default response content is text/html
-   [] None

### CODE REVIEW

**Comment by mmoayyed** [comment]
Excellent. Please merge with master once and resolve conflicts so we can proceed. Thank you.

**Comment by mmoayyed** [comment]
Have you had a chance to merge this with master once and resolve conflicts?

**Comment by fedon** [comment]
Conflict is too complex to resolve. I better provide brand new forward port.

**Comment by mmoayyed** [comment]
Great. Thanks.

**Comment by mmoayyed** [comment]
Have you had a chance to provide a patch for master?

**Pull request closed without merging**
