### PR TITLE
Fix incompatibility with Sentry

### PR DESCRIPTION
**Pull request by leleuj**
This PR fixes an incompatibility with Sentry and defining the property `management.server.port`.

The solution was to change the interface used for bean creation (like https://github.com/apereo/cas/commit/827ccd8585797fb3b36d987a7a461d97c2ef0f15).

The `login-success` Puppeteer has been updated to confirm the fix (`./ci/tests/puppeteer/run.sh --rebuild --scenario ./ci/tests/puppeteer/scenarios/login-success`).

Locally, I also successfully run:
- `./gradlew cleanTest testWebApp --no-configuration-cache -p webapp/cas-server-webapp-init-tomcat`
- `./gradlew clean build check javadoc -no-configuration-cache -p support/cas-server-support-sentry`
- `./gradlew clean build check javadoc -no-configuration-cache -p  webapp/cas-server-webapp-init-tomcat`

### CODE REVIEW

**Review by mmoayyed — CHANGES_REQUESTED** [review]
Thank you for the report and the fix.

This is not something we can accept. There are multiple "issues" with the fix:

1. The entire point of tracing is that you, well, trace, Excluding components from the trace specially when it's not obvious why is problematic and defeats the purpose of doing so.
2. The Sentry module cannot have "hard" connections to anything else outside the model statically. Otherwise, 3 months from now that list of exclusions is going to grow and grow and would be unmaintainable.
3. If we ever move a class to some other package, the fix immediately becomes invalid.
4. This is not a fix, really. The issue has to do with the fact that the objects in question are not created with a proper interface and instead they are defined as a concrete class in various injections which makes proxying fail. If you fix this, the problem goes away.

**Comment by leleuj** [comment]
Sorry for the delay on this. I resume my work today.

**Comment by leleuj** [comment]
I cannot reproduce the issue and I see that you have fixed it: https://github.com/apereo/cas/commit/827ccd8585797fb3b36d987a7a461d97c2ef0f15

**Comment by leleuj** [comment]
I'm not closing it yet as I have spotted another issue...

**Comment by leleuj** [comment]
@mmoayyed Please find another fix related to Sentry...

**Comment by mmoayyed** [comment]
Looks good, thank you. We'll wait for CI to pass and then the bot should merge.

**Pull request merged**
