### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by dima767**
Remove powered by IDEA

### CODE REVIEW

**Comment by mmoayyed** [comment]
Not sure I agree with this change. Why?

**Comment by dima767** [comment]
Is Jetbrains providing open source license for development of CAS? If not, I'd not sure that the CAS project should advertise them

**Comment by mmoayyed** [comment]
Providing a free license is one thing. Having the tool power development is another. We are not advertising usage. Just that we most commonly use the tool to build the software. For what it's worth, the eclipse logo might also be there too. That's probably a better change for this PR.

**Comment by dima767** [comment]
Oh, well, we agree to disagree ;-) Feel free to kill this PR.

**Comment by mmoayyed** [comment]
Sounds good. Thanks!

**Pull request closed without merging**
