### PR TITLE
Basic framework for attribute editing

### PR DESCRIPTION
**Pull request by marwatk**
This is an add on module for editing attributes within cas. 

It's very rough so far, it won't even build successfully yet. None of it is wired up and I still have some understanding to figure out with regard to how properties load, there are a ton of style issues, etc, etc -- but I believe all of the conceptual pieces are there to give an overview of the approach. I wanted to get it visible as quickly as possible to try to make the 5.2 release window.

Feedback is encouraged, there are a few pieces I'm not super happy with (bringing EditableAttributeRepository and EditableAttributeValueRepository together in a clean way, really). I should have it finished up and tested tomorrow or Friday, hopefully.

### CODE REVIEW

**Comment by mmoayyed** [comment]
Thank you for the PR. 

Could you please describe:

1. What exactly is the intention of this pull request? What problem does it solve, and why?
2. What, at a high level, are the key components here?
3. What, at a high level, is the user-facing functionality?

I recommend you close the pull request and start at smaller chunks. We simply will not be able to review and merge a batch that has 36 files changes with all new functionality in time, and it's likely this will go stale for a long time.

**Comment by marwatk** [comment]
In my head there was a perfect connection between this and the discussion we were having two days ago, but now I'm realizing most of the connections we're in my head :)

This is for password question management.

Here's the original discussion: https://github.com/apereo/cas/issues/2950

When implenting it, I realized there's no good reason to just leave it at password questions. Providing for those gets you 99% of the way to editing (mostly) any attribute. So this PR is a generic version of attribute management.

It's almost a direct copy of the aup module, with the distinction that there are two repository types. `EditableAttributeRepository` stores settings about the attributes (see the changes made to the config doc). `EditableAttributeValueRepositories` store the actual values in the user (via ldap, rest or jdbc modules).

There is an associated web flow module, view and properties object to accommodate everything. 

I'm not sure how we could break it up into smaller chunks, though. This is pretty much the smallest implementation that would support various drivers. I could remove the drivers and config hooks, allowing only for custom implementations? Open to suggestions there...

**Comment by mmoayyed** [comment]
Ah gotcha. As I was browsing through the files I was expecting things to be more PMish :) and couldn't quite make out the connection between that and what you consider an editable attribute. 

So ok, you essentially have put together designs where CAS would be able to generically edit a given attribute from some sort of data source backend, and one class of attributes would be those that deal with security questions. So far, so good. I understand the motivation where today, there exist islands of similar functionality that deal with AUP and such and I guess you were inspired to kill many birds with one design. Very good!

However, I recommend that you back out most changes and solely/exclusively focus on a smaller problem with a much smaller scope that only deals with security questions and attributes associated with those. It might seem counter-productive but I am in fact recommending that you should perhaps go for yet another island. My recommendations stems from the fact that I believe the work you are doing, while great as it can be, is a little **premature**, for the following reasons:

1. The password management functionality in CAS is fairly new; in fact most "serious" deployments would end up deploying a separate standalone app altogether to handle that sort of thing. While I personally have high hopes for this thing in CAS today to take off and remove that need, the reality is that the margin is far too narrow to dedicate an entire framework and technical batch to handle more advanced operations such as this more generically. I could be entirely wrong here of course, and I also suggest you shoot a message to the cas mailing lists and ask around; if there is enough interest to spend time and energy maintaining this for the broader masses and have other modules leverage this behavior, by all means. Happy to jump on board, but it seems like something of a nuclear power plant designed to power a light bulb. 

2. Another factor in me hesitating is that sort of framework you're working on where CAS ends up updating essentially an identity store is not quite a good fit for CAS. As a general framework allowing CAS to edit attributes and principal data, the work seems overkill given most "serious" deployments have dedicated IDM solutions solely tasked for that sort of thing where CAS simply becomes a consumer. Much of that framework already exists outside, and will continue to live as such with complex rules and engines provisioning things here and there. The sort of "update" ops CAS ends up doing mostly deal with one attribute here as a boolean and few over there for blah. Fairly limiting and very focused. This is why I recommend you focus on a much smaller problem; I can promise you that the adoption of the "general framework" would be rare and eventually, I am afraid, it will end up as code once written and then deleted only to remain as an extension for you. 

Please don't this the wrong way; I am not certainly referring to your needs as "not serious" and I am rarely one to call something "outside of core vision". (In fact I wrote a whole blog post about the exact opposite) I think everything is in scope given proper demand and adoption possibility at the right time and I don't see this amount work would be worth it right now; but that's just me. I certainly do not want to discourage you from contributing, but a few more convincing votes would be great to express larger interest around the overall design of this possibly extracted from the mailing lists, etc. 

I am also going to ping @frett @tsschmi @dima767 to name a few to see what they might have to say, as more active contributors to the project.

**Comment by marwatk** [comment]
That makes sense, though it's worth pointing out that while it touches a lot of files, it's really not much more complex or involved than the aup or consent modules. And it certainly doesn't aim to replace any of them. 

But it absolutely could end up never being used outside of our implementation. We don't run a separate identity management system, it's overkill for our needs. But we do require password question answers (and couple other attributes) so we end up having to create that management ourselves.

I'd be willing to back it up to only deal with password management if you feel that would be a better fit. After all, that's really the same code just with less configuration. Ideally I could hook it such that it would be possible to extend.

**Comment by mmoayyed** [comment]
> I'd be willing to back it up to only deal with password management if you feel that would be a better fit. After all, that's really the same code just with less configuration. Ideally I could hook it such that it would be possible to extend.

Excellent. I think this would be a pretty good action plan; bonus points for extension policies later on which helps should use cases and scope ever grow beyond what we think they are today :)

Thanks very much.

**Comment by marwatk** [comment]
I've been thinking about it all night and I'm having trouble coming up with a less complicated solution, even for just embedding it in the pm module. I think I'd end up touching the exact same number of files either way. The crux of the issue comes back to storage and validation of available password questions.

When simply displaying them it's easy, you just grab what's there and present it. But for editing you can't just have a predefined set of 3 questions -- some users' mothers may not have a maiden name, for example. So the allowable questions need to be stored somewhere resulting in another storage mechanism somewhere. Then you need to ensure they fill it out properly (not choosing the same question twice, etc) so you need a validator in there somewhere. Plus each driver needs to know how to update them, etc, etc.

When all is said and done you're at the same place we are here with this module. :/

Here's a breakdown of the files modified, why they're needed, and if/where they'd still be needed in an add-on to pm:

New File | Purpose | Associated pm change
-- | -- | --
CasConfigurationProperties | Map settings to cas properties | None
EditableAttributeProperties | Store settings | PasswordManagementProperties
Configuration-Properties.md | Docs change | Same
settings.gradle | Link to new modules | None
build.gradle | Module build file (core) | None
EditableAttributeRepository | Interface to retreive available questions | New equivalent
DefaultEditableAttributeRepository | Default implementation of above | New equivalent
EditableAttributeValueRepository | Interface to retrieve question answers | PasswordManagementService
AbstractPrincipalEditable AttributeValueRepository | Retrieve available question options | None?
DefaultEditableAttribute ValueRepository | Interface to set questions and answers | BasePasswordManagementService
EditableAttributeValueValidator | Interface to validate questions/answers | New equivalent
DefaultEditableAttributeValueValidator | Default implementation of above | New equivalent
build.gradle | Module build file (jdbc) | None
JdbcEditableAttributeValueRepository | JDBC driver | JdbcPasswordManagementService
CasEditableAttributeJdbcConfiguration | JDBC Configuration | PasswordManagementProperties
spring.factories | (jdbc) | None
JdbcEditableAttributeValueRepositoryTest | Test cases | None
build.gradle | Module build file (ldap) | None
LdapEditableAttributeValueRepository | LDAP Driver | LdapPasswordManagementService
CasEditableAttributeLdapConfiguration | LDAP Configuration | PasswordManagementProperties
spring.factories | driver loader | None
build.gradle | Module build file (rest) | None
RestEditableAttributeValueRepository | Rest driver | RestPasswordManagementService
CasEditableAttributeRestConfiguration | Rest configuration | PasswordManagementProperties
spring.factories | driver loader | None
build.gradle | Module build file (flow) | None
CasEditableAttribute WebflowConfiguration | Web flow configuration | PasswordManagementWebflowConfiguration
EditableAttributeFormAction | Form action for saving answers | New equivalent
EditableAttributeWebflowConfigurer | Configure web flow | PasswordManagementWebflowConfigurer
spring.factories | driver loader | None
messages.properties | Button labels | Same
casEditableAttributesView.html | View for displaying form | Same

Of the 32 new/edited files 10 are build files or related (spring.factories, build.gradle, etc). 19 would still be required in some form whether directly in the pm or a sub module, leaving only 2-3 fewer new/changed files. The total lines of changed code would be roughly equivalent, except now they'd be sprinkled in with existing code instead of isolated into their own module.

I'm willing to try it, but I feel like it's not an obviously 'better' solution, or even more likely to be accepted. For us it's worse because we'd have to modify the result in an overlay to support our use case.

**Pull request closed without merging**
