### PR TITLE
Add FreeIPA account status support to LPPE

### PR DESCRIPTION
**Pull request by tduehr**
Add support for FreeIPA error values.

`errorMap` might be better replaced with calls to `AccountState#handleError()` instead.

### CODE REVIEW

**Comment by mmoayyed** [comment]
Cool. Could you fix the compile errors?

**Comment by tduehr** [comment]
This seems to require ldaptive 1.2.0-SNAPSHOT

**Comment by mmoayyed** [comment]
Ok. Let's let it hang until this is resolved https://github.com/vt-middleware/ldaptive/issues/82

**Comment by tduehr** [comment]
I'm trying to use it as is but the only thing being thrown is a general AuthenticationException. I'm never redirected to the password change URL despite the log saying it's handling `PASSWORD_EXPIRED`.

**Comment by tduehr** [comment]
Otherwise, it works just fine for me.

**Comment by tduehr** [comment]
Seems like it may be related in some way to https://github.com/apereo/cas/pull/646. Looking at the webflow for login, both the `casMustChangePassView` and `casExpiredPassView` point to the same place `abstactPasswordChangeView` but neither are being hit.

**Comment by mmoayyed** [comment]
Share logs plz.

**Comment by tduehr** [comment]
I'm afraid they're less than useful... this is with `org.jasig.cas.authentication.support` and `org.jasig.cas.web.flow` at debug. I'll post a wider one w/ all of `org.jasig.cas.authentication` in a bit.

https://gist.github.com/anonymous/7f6c3d0a72c568700a266bab81619f83

**Comment by mmoayyed** [comment]
Cool, thanks. I just wanted to see how easy this would be to duplicate. Fairly trivial as it turns out.

What you want to do is turn up logs for `org.springframework.webflow` or some such, to trace the flow after the account state is handled. Set that to DEBUG and post back please.

**Comment by tduehr** [comment]
This one is more useful:

https://gist.github.com/anonymous/a05bbde1756126e5a846c3a47e43c02f

**Comment by mmoayyed** [comment]
This works perfectly fine as far as I can see. You are just missing properties. Specially this one: passwordPolicy.passwordPolicyUrl

**Comment by mmoayyed** [comment]
To be fair, I didn't look to see how the flow scope is populated with that property, but that's what the issue here is. The views are fine it seems.

**Comment by tduehr** [comment]
The old property was `password.policy.url` I had that one set.

After adding `passwordPolicy.passwordPolicyUrl` to my config, I still get the same error.

I think I found it... I'm using ldaptive1.2 which doesn't use `usePasswordPolicy` anymore. I'll troll through the ldaptive 1.2 branch to see what I missed in my own patches.

**Comment by tduehr** [comment]
~~~
        <ldaptive:authentication-response-handler>
            <ldaptive:free-ipa-handler
                expirationPeriod="${ldap.auth.expirationPeriod}"
                warningPeriod="${ldap.auth.warningPeriod}"
                maxLoginFailures="${ldap.auth.maxLoginFailures:0}" />
        </ldaptive:authentication-response-handler>
~~~

Looks like I have a bug to find...

**Comment by tduehr** [comment]
Got it! incoming PR.

**Comment by tduehr** [comment]
Would it be easier for me to target unicon/ldaptive1.2 on this?

**Comment by mmoayyed** [comment]
Yeah I think so.

**Comment by tduehr** [comment]
Done

**Pull request closed without merging**
