### PR TITLE
Use constructor based injection

### PR DESCRIPTION
**Pull request by DavidRG13**
Part of #2184

Remove setters from themes module

### CODE REVIEW

**Comment by mmoayyed** [comment]
@DavidRG13 as you go through these changes, please ignore the saml-idp module for now. Working on a few changes ATM and I'd like to minimize merge conflicts.

**Comment by mmoayyed** [comment]
Of course, if you have already done that one it's perfectly fine. We shall merge.

**Comment by DavidRG13** [comment]
Don't worry mate, working on another module

**Comment by mmoayyed** [comment]
Excellent. One thing I noticed by the way: recent changes broke master at runtime. When you change type information for generic collections in beans, you must make sure all instances of that bean are changed.

For instance, if the bean is:

```
public List<Object> someList() {}
```

Make sure all references to it are also changed:

```
@Autowired
@Qualifier("someList")
private List<Object> list;
```

Leaving it like:

```
@Autowired
@Qualifier("someList")
private List list;
```

causes breakage.

**Pull request merged**
