### PR TITLE
fix: kryo serialization problems with memcached

### PR DESCRIPTION
**Pull request by jgribonvald**
This PR intends to fix kryo problems with memcached.
The first commit try to show problems
The second commit will fix problems

### CODE REVIEW

**Comment by jgribonvald** [comment]
Is there a way to add a test with the creation of a ticket (TGT + PT) corresponding of a such service declaration ? It's only to be able to reproduce the problem from a test.

**Comment by mmoayyed** [comment]
If you examine `CasKryoTranscoderTests`, you'll find tests that attempt to handle proxy tickets, etc.

Could you also attach the failure log output from your *first* commit? What is the error you'd get?

**Comment by jgribonvald** [comment]
Sorry here are logs:

**Comment by jgribonvald** [comment]
sorry here are logs:

```log
00:00  WARN: [kryo] Unable to load class E with kryo's ClassLoader. Retrying with current..
2019-03-08 14:28:51,658 ERROR [org.apereo.cas.ticket.registry.MemcachedTicketRegistry] - <Failed fetching [PGT-1-*****XXXXXXXXXXXX] >
java.lang.RuntimeException: Exception waiting for value
	at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1236) ~[spymemcached-2.12.3.jar!/:2.12.3]
	at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1256) ~[spymemcached-2.12.3.jar!/:2.12.3]
...
Caused by: java.util.concurrent.ExecutionException: com.esotericsoftware.kryo.KryoException: com.esotericsoftware.kryo.KryoException: Unable to find class: E
Serialization trace:
principalAttributesRepository (org.apereo.cas.services.ReturnAllowedAttributeReleasePolicy)
service (org.apereo.cas.authentication.credential.HttpBasedServiceCredential)
credentialMetaData (org.apereo.cas.authentication.DefaultAuthenticationHandlerExecutionResult)
successes (org.apereo.cas.authentication.DefaultAuthentication)
authentication (org.apereo.cas.ticket.ProxyGrantingTicketImpl)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at net.spy.memcached.transcoders.TranscodeService$Task.get(TranscodeService.java:97) ~[spymemcached-2.12.3.jar!/:2.12.3]
	at net.spy.memcached.internal.GetFuture.get(GetFuture.java:70) ~[spymemcached-2.12.3.jar!/:2.12.3]
	at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1229) ~[spymemcached-2.12.3.jar!/:2.12.3]
	... 135 more
```

At the first authentication I'm getting this log before:
```log
00:15  WARN: Class is not registered: org.apereo.cas.authentication.principal.DefaultPrincipalAttributesRepository
Note: To register this class use: kryo.register(org.apereo.cas.authentication.principal.DefaultPrincipalAttributesRepository.class);
```

With the latest version from master branch (after rebased) I had also one more same error with Object[].class.


After my problem with providing a test case is on how to contruct a ticket from a such service declaration example (from service registry of my test)
```json
{
  "@class" : "org.apereo.cas.services.RegexRegisteredService",
  "serviceId" : "^(https|imaps)://.*",
  "name" : "local",
  "id" : 10001,
  "evaluationOrder" : 99999,
  "desciption" : "Tous les services de la plateforme en test",
  "usernameAttributeProvider" : {
    "@class" : "org.apereo.cas.services.PrincipalAttributeRegisteredServiceUsernameProvider",
    "usernameAttribute" : "uid",
    "canonicalizationMode" : "NONE"
  },
  "attributeReleasePolicy" : {
    "@class" : "org.apereo.cas.services.ReturnAllowedAttributeReleasePolicy",
    "allowedAttributes" : [ "java.util.ArrayList", [ "cn", "mail", "isMemberOf" ] ]
  },
  "proxyPolicy" : {
    "@class" : "org.apereo.cas.services.RegexMatchingRegisteredServiceProxyPolicy",
    "pattern" : "^(https|imaps)://.*"
  }
}
```
Note the first commit doesn't permit to reproduce the error, but it should help if we have a test case to generate an error if an authentication is made, it will generate an error instead of a warning like in logs provided.

**Comment by mmoayyed** [comment]
Thank you very much for the contribution!

**Comment by jgribonvald** [comment]
you're welcome :smiley:

**Pull request merged**
