### PR TITLE
Docs fix to #2449

### PR DESCRIPTION
**Pull request by fedon**
Documentation fix.

### CODE REVIEW

**Comment by PetrGasparik** [comment]
Misagh, can you rerun this travis, so we can check output in doc?
https://travis-ci.org/apereo/cas/builds/211358884

**Comment by mmoayyed** [comment]
Sure

**Comment by PetrGasparik** [comment]
Unfortunately, it did fail again:

Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find opensaml-storage-api.jar (org.opensaml:opensaml-storage-api:3.3.0).
Searched in the following locations:
    https://repo1.maven.org/maven2/org/opensaml/opensaml-storage-api/3.3.0/opensaml-storage-api-3.3.0.jar

Can you resolve that in artifactory and rerun build? Thanks!

**Comment by mmoayyed** [comment]
Yes I am looking into this. Thanks for spotting it. 

Travis is just being weird. It will eventually sort itself out. I know there were a few outages recently and I am not sure if it's still them or something CAS does that makes it go haywire. We'll figure it out.

**Comment by mmoayyed** [comment]
It *looks* as though we are back in business. Keep watch please and as always, if you find anything else that is broken and needs attention, shoot over patches.

**Pull request merged**
