### PR TITLE
Fix Password Reset Request Verification

### PR DESCRIPTION
**Pull request by julienhuon**
Hello Misagh,

When you're using the password reset feature in CAS, you will receive a mail or a sms with a reset link associated with a token in the registry.

Unfortunately, in the versions 6.2 and 6.3, if the link has already been used or has expired and doesn't appears in the registry, you'll have the following error in the web page:

```
Error: Exception thrown executing org.apereo.cas.pm.web.flow.actions.VerifyPasswordResetRequestAction@4af8ff3 in state 'verifyPasswordResetRequest' of flow 'pswdreset' -- action execution attributes were 'map[[empty]]'
```
It's because the method "getTicket" from "centralAuthenticationService" raise an exception if the ticket doesn't exists instead of provide a null response.

Here a little fix to solve the problem.

Regards,
Julien

### CODE REVIEW

**Comment by mmoayyed** [comment]
Thank you. Please review the failures and adjust accordingly.

**Comment by julienhuon** [comment]
Hi,

The only failing job is the filesystem one but I doesn't seems related to the code : 

```
https://codecov.io/upload/v4?package=bash-20200728-9fb7d93&token=secret&branch=pmreset&commit=b12c494473323cb3c1cfd3665baf596aa6039f0d&build=213263246&build_url=http%3A%2F%2Fgithub.com%2Fapereo%2Fcas%2Factions%2Fruns%2F213263246&name=&tag=&slug=apereo%2Fcas&service=github-actions&flags=filesystem&pr=4925&job=&cmd_args=n,F,Z
HTTP 400

ERROR: Tokenless uploads are only supported for public repositories on GitHub Actions that can be verified through the Actions API. Please use an upload token if your repository is private and specify it via the -t flag. You can find the token for this repository at the url below on codecov.io (login required):

Repo token: https://codecov.io/gh/apereo/cas/settings
Documentation: https://docs.codecov.io/docs/about-the-codecov-bash-uploader#section-upload-token
##[error]Codecov failed with the following error: The process 'bash' failed with exit code 1
```

Regards,
Julien

**Comment by mmoayyed** [comment]
That's not the failure.

image

**Comment by julienhuon** [comment]
> 
> 
> That's not the failure.
> 
> image

Ok

**Comment by julienhuon** [comment]
Hi @mmoayyed,

I saw that you fixed the error and added tests. I guess I should close this PR now and delete my work ?

Do you mind if I let my other PR open and backport in it your changes in the 6.2 branch ?

Regards,
Julien

**Comment by mmoayyed** [comment]
You are welcome to backport. I wasn't necessarily trying to fix the issue here; mainly wanted to improve test coverage and so this got fixed by accident really :)

**Comment by julienhuon** [comment]
No problem at all. :)

**Pull request closed without merging**
