### PR TITLE
Doc fix.

### PR DESCRIPTION
**Pull request by uprego**
Consolidate documentation considerations coming from the https://groups.google.com/d/msg/jasig-cas-user/N7wcNVMtES0/uoqSQmYCBAAJ thread of the user mailing list.

Regards,

### CODE REVIEW

**Comment by uprego** [comment]
I see you cherry picked it from the `master` and `5.2.x` branches, and those commits got the GitHub pages branch (`gh-pages`) receiving one commit updating the `/development/` online docs and another updating the `/5.2.x/` online docs. But a rev updating the `/5.1.x/` online docs has not been generated. Why could that be? Is the docs auto update disabled/broken for the `5.1.x` branch? Is it waiting for a commit of yours @mmoayyed?

**Comment by mmoayyed** [comment]
You will need to submit another pull request with the same change targetting the 5.1.x branch instead.

**Comment by uprego** [comment]
It seems the bot updated it at last several hours ago :grin:.

**Comment by mmoayyed** [comment]
There are no bots! :) Only people masquerading as bots.

**Pull request merged**
