### PR TITLE
OIDC state not send back to logout redirect

### PR DESCRIPTION
**Pull request by johnjcool**
OIDC state not send back to logout redirect - especially keycloak need this state to remove session on logout

### CODE REVIEW

**Comment by johnjcool** [comment]
I am disappointed to get no feedback from any cas core developer... whether on github nor on Gitter. The build problem are LDAP tests. Not my fault. The branch is broken. Did you really want help to fix bugs? Think about your communication strategy.

**Comment by hdeadman** [comment]
I don't think there is a communication strategy but there isn't currently anyone being paid to review PRs or monitor gitter and I am not aware of any commitment by anyone to review PRs in a certain amount of time. My experience is that PRs are looked at eventually but paid work takes priority over volunteer work. 

Regarding the LDAP test, I will try to look into that as it may be a result of me updating the samba image that is used by that test, but that will be added to a list of things I should be working on personally and professionally.

**Comment by hdeadman** [comment]
If you merge latest commit from 6.1.x to your PR it should pass the LDAP test now.

**Comment by johnjcool** [comment]
thanks

**Comment by johnjcool** [comment]
download dependencies is broken

**Comment by johnjcool** [comment]
@hdeadman:  i thought about your words. your right paid work is better than free work. but analyzing bugs, fixing bugs and testing with an productive environment and giving it back to the core could also be paid work. it helps you to get a stable product which would be lovely used by others. a code review and clicking the merge button is not asking too much.

**Comment by mmoayyed** [comment]
Thanks much for the patch.

As Hal indicates, reviewing code, porting changes back and forth, cutting releases and the general maintenance and upkeep of the software at the moment is 100% voluntary. It takes time and effort, and however small that might seem to you, it's something that needs to be judiciously spent in view of all other professional and personal responsibilities, just like you do. Other than what is outlined in the contribution guidelines (which is the only "communication strategy" we have and I recommend you review it and update patches accordingly to expedite the process), there are no other commitments, expectations, promises guarantees. You may get a response in 3 seconds, or 3 years. If you need something more solid and this model is not acceptable to you, (however small that effort might seem to you), please reach out to Apereo to discuss membership or review support options listed on the site, or fork/patch and move at your own pace.

I appreciate your effort to contribute, truly. You just have to be patient until we find the time incentive and patience to review things with you and move forward. It might be slow, and it might be really slow, but that's how things are at the moment with volunteer effort and state of financial support. There are other priorities. If you need to remind someone to work and collaborate with you, a gentle reminder on the patch would be helpful. Please try to refrain passive aggressive responses or needless arguments/debates. Those will not help with progress.

Contribution guidelines are available here: https://apereo.github.io/cas/developer/Contributor-Guidelines.html#why-isnt-my-proposal-accepted-and-merged-yet

If you find that your patch does not meet the criteria, please make adjustments. If you do find that there are blocking factors not related to your patch, please communicate that clearly and kindly and someone in due time will try to accommodate as schedules allow.

**Pull request merged**
