### PR TITLE
Not configured attribute mapping relationship, you also should get at…

### PR DESCRIPTION
**Pull request by zawn**
Not configured attribute mapping relationship, you also should get attributes

### CODE REVIEW

**Comment by mmoayyed** [comment]
What exactly does this PR accomplish?

**Comment by zawn** [comment]
image

org.apereo.services.persondir.support;


 when user does not configure the property ,casProperties.getAuthn () getAttributeRepository () getAttributes () should return null, can not  return empty。If it is empty then discard

**Comment by mmoayyed** [comment]
When the user does not configure the property the collection of attributes simply remain as empty. They are not null, and should not be null. If nothing is defined, you don't get a DAO.

**Comment by mmoayyed** [comment]
Ah, I see what you mean. So person directory attempts to use attributes as-is when no mapping is defined for JDBC DAOs. Correct?

**Comment by mmoayyed** [comment]
This makes sense to me. Thanks for the contribution. Fix the problems reported on the PR and we should be good to merge.

**Comment by zawn** [comment]
Sorry, English is not very good, especially to describe the technical terms

**Comment by mmoayyed** [comment]
No worries. I understand:)

**Pull request merged**
